/* Pokémon: Distortion Rift — core data: types, chart, moves, items, species */
window.G = window.G || {};
G.Data = G.Data || {};

/* ---------------- TYPES ---------------- */
G.Data.TYPES = ["Normal","Fire","Water","Electric","Grass","Ice","Fighting","Poison",
"Ground","Flying","Psychic","Bug","Rock","Ghost","Dragon","Dark","Steel","Fairy"];

/* Standard Gen 6+ type chart. Missing entries = 1x. */
G.Data.CHART = {
  Normal:   {Rock:0.5, Ghost:0, Steel:0.5},
  Fire:     {Fire:0.5, Water:0.5, Grass:2, Ice:2, Bug:2, Rock:0.5, Dragon:0.5, Steel:2},
  Water:    {Fire:2, Water:0.5, Grass:0.5, Ground:2, Rock:2, Dragon:0.5},
  Electric: {Water:2, Electric:0.5, Grass:0.5, Ground:0, Flying:2, Dragon:0.5},
  Grass:    {Fire:0.5, Water:2, Grass:0.5, Poison:0.5, Ground:2, Flying:0.5, Bug:0.5, Rock:2, Dragon:0.5, Steel:0.5},
  Ice:      {Fire:0.5, Water:0.5, Grass:2, Ice:0.5, Ground:2, Flying:2, Dragon:2, Steel:0.5},
  Fighting: {Normal:2, Ice:2, Poison:0.5, Flying:0.5, Psychic:0.5, Bug:0.5, Rock:2, Ghost:0, Dark:2, Steel:2, Fairy:0.5},
  Poison:   {Grass:2, Poison:0.5, Ground:0.5, Rock:0.5, Ghost:0.5, Steel:0, Fairy:2},
  Ground:   {Fire:2, Electric:2, Grass:0.5, Poison:2, Flying:0, Bug:0.5, Rock:2, Steel:2},
  Flying:   {Electric:0.5, Grass:2, Fighting:2, Bug:2, Rock:0.5, Steel:0.5},
  Psychic:  {Fighting:2, Poison:2, Psychic:0.5, Dark:0, Steel:0.5},
  Bug:      {Fire:0.5, Grass:2, Fighting:0.5, Poison:0.5, Flying:0.5, Psychic:2, Ghost:0.5, Dark:2, Steel:0.5, Fairy:0.5},
  Rock:     {Fire:2, Ice:2, Fighting:0.5, Ground:0.5, Flying:2, Bug:2, Steel:0.5},
  Ghost:    {Normal:0, Psychic:2, Ghost:2, Dark:0.5},
  Dragon:   {Dragon:2, Steel:0.5, Fairy:0},
  Dark:     {Fighting:0.5, Psychic:2, Ghost:2, Dark:0.5, Fairy:0.5},
  Steel:    {Fire:0.5, Water:0.5, Electric:0.5, Ice:2, Rock:2, Steel:0.5, Fairy:2},
  Fairy:    {Fire:0.5, Fighting:2, Poison:0.5, Dragon:2, Dark:2, Steel:0.5}
};

/** Effectiveness multiplier for an attacking type vs 1-2 defending types. */
G.Data.effVs = function(atkType, defTypes){
  var chart = G.Data.CHART[atkType] || {};
  var m = 1;
  (defTypes || []).forEach(function(t){ m *= (chart[t] === undefined ? 1 : chart[t]); });
  return m;
};

/* ---------------- MOVES ----------------
   cat: phys | spec | status. eff keys: stat, foeStat, status, statusChance,
   heal, recoil, drain, flinch, priority, hits. */
G.Data.MOVES = {
tackle:{id:"tackle",name:"Tackle",type:"Normal",cat:"phys",pow:40,acc:100,pp:35,eff:{},desc:"A full-body charge."},
"quick-attack":{id:"quick-attack",name:"Quick Attack",type:"Normal",cat:"phys",pow:40,acc:100,pp:30,eff:{priority:1},desc:"Strikes first with blinding speed."},
scratch:{id:"scratch",name:"Scratch",type:"Normal",cat:"phys",pow:40,acc:100,pp:35,eff:{},desc:"Rakes with sharp claws."},
pound:{id:"pound",name:"Pound",type:"Normal",cat:"phys",pow:40,acc:100,pp:35,eff:{},desc:"A heavy slam."},
"body-slam":{id:"body-slam",name:"Body Slam",type:"Normal",cat:"phys",pow:85,acc:100,pp:15,eff:{status:"par",statusChance:30},desc:"May paralyze the foe."},
"double-edge":{id:"double-edge",name:"Double-Edge",type:"Normal",cat:"phys",pow:120,acc:100,pp:15,eff:{recoil:0.33},desc:"Huge damage, hurts the user."},
facade:{id:"facade",name:"Facade",type:"Normal",cat:"phys",pow:70,acc:100,pp:20,eff:{},desc:"An all-out strike."},
slash:{id:"slash",name:"Slash",type:"Normal",cat:"phys",pow:70,acc:100,pp:20,eff:{},desc:"Slashes with claws."},
"fury-swipes":{id:"fury-swipes",name:"Fury Swipes",type:"Normal",cat:"phys",pow:18,acc:80,pp:15,eff:{hits:[2,5]},desc:"Hits 2-5 times."},
"hyper-voice":{id:"hyper-voice",name:"Hyper Voice",type:"Normal",cat:"spec",pow:90,acc:100,pp:10,eff:{},desc:"A deafening shout."},
swift:{id:"swift",name:"Swift",type:"Normal",cat:"spec",pow:60,acc:100,pp:20,eff:{},desc:"Star-shaped rays that never miss."},
"tri-attack":{id:"tri-attack",name:"Tri Attack",type:"Normal",cat:"spec",pow:80,acc:100,pp:10,eff:{status:"par",statusChance:10},desc:"Fires three beams at once."},
"karate-chop":{id:"karate-chop",name:"Karate Chop",type:"Fighting",cat:"phys",pow:50,acc:100,pp:25,eff:{},desc:"A sharp chop."},
"mach-punch":{id:"mach-punch",name:"Mach Punch",type:"Fighting",cat:"phys",pow:40,acc:100,pp:30,eff:{priority:1},desc:"A blindingly fast punch."},
"brick-break":{id:"brick-break",name:"Brick Break",type:"Fighting",cat:"phys",pow:75,acc:100,pp:15,eff:{},desc:"Smashes through defenses."},
"cross-chop":{id:"cross-chop",name:"Cross Chop",type:"Fighting",cat:"phys",pow:100,acc:80,pp:5,eff:{},desc:"A double-chop smash."},
"close-combat":{id:"close-combat",name:"Close Combat",type:"Fighting",cat:"phys",pow:120,acc:100,pp:5,eff:{stat:{def:-1,spd:-1}},desc:"All-out brawl; lowers defenses."},
superpower:{id:"superpower",name:"Superpower",type:"Fighting",cat:"phys",pow:120,acc:100,pp:5,eff:{stat:{atk:-1,def:-1}},desc:"Raw might that tires the user."},
"drain-punch":{id:"drain-punch",name:"Drain Punch",type:"Fighting",cat:"phys",pow:75,acc:100,pp:10,eff:{drain:0.5},desc:"Heals half the damage dealt."},
"vacuum-wave":{id:"vacuum-wave",name:"Vacuum Wave",type:"Fighting",cat:"spec",pow:40,acc:100,pp:30,eff:{priority:1},desc:"A first-strike shockwave."},
"aura-sphere":{id:"aura-sphere",name:"Aura Sphere",type:"Fighting",cat:"spec",pow:80,acc:100,pp:20,eff:{},desc:"An aura blast that never misses."},
"focus-blast":{id:"focus-blast",name:"Focus Blast",type:"Fighting",cat:"spec",pow:120,acc:70,pp:5,eff:{foeStat:{spd:-1}},desc:"Unstable but devastating."},
"secret-sword":{id:"secret-sword",name:"Secret Sword",type:"Fighting",cat:"spec",pow:85,acc:100,pp:10,eff:{},desc:"A spectral blade of resolve."},
"sacred-sword":{id:"sacred-sword",name:"Sacred Sword",type:"Fighting",cat:"phys",pow:90,acc:100,pp:15,eff:{},desc:"A noble blade that cuts through evil."},
"collision-course":{id:"collision-course",name:"Collision Course",type:"Fighting",cat:"phys",pow:100,acc:100,pp:5,eff:{},desc:"Koraidon's full-body tackle."},
peck:{id:"peck",name:"Peck",type:"Flying",cat:"phys",pow:35,acc:100,pp:35,eff:{},desc:"Jabs with the beak."},
"wing-attack":{id:"wing-attack",name:"Wing Attack",type:"Flying",cat:"phys",pow:60,acc:100,pp:35,eff:{},desc:"Slams with broad wings."},
"aerial-ace":{id:"aerial-ace",name:"Aerial Ace",type:"Flying",cat:"phys",pow:60,acc:100,pp:20,eff:{},desc:"An unavoidable slash."},
"drill-peck":{id:"drill-peck",name:"Drill Peck",type:"Flying",cat:"phys",pow:80,acc:100,pp:20,eff:{},desc:"A spinning corkscrew peck."},
"brave-bird":{id:"brave-bird",name:"Brave Bird",type:"Flying",cat:"phys",pow:120,acc:100,pp:15,eff:{recoil:0.33},desc:"A reckless sky dive."},
"air-slash":{id:"air-slash",name:"Air Slash",type:"Flying",cat:"spec",pow:75,acc:95,pp:15,eff:{flinch:30},desc:"Razor wind that may flinch."},
hurricane:{id:"hurricane",name:"Hurricane",type:"Flying",cat:"spec",pow:110,acc:70,pp:10,eff:{},desc:"A raging storm."},
aeroblast:{id:"aeroblast",name:"Aeroblast",type:"Flying",cat:"spec",pow:100,acc:95,pp:5,eff:{},desc:"Lugia's whirlwind blast."},
"oblivion-wing":{id:"oblivion-wing",name:"Oblivion Wing",type:"Flying",cat:"spec",pow:80,acc:100,pp:10,eff:{drain:0.75},desc:"Yveltal's life-draining wings."},
"poison-jab":{id:"poison-jab",name:"Poison Jab",type:"Poison",cat:"phys",pow:80,acc:100,pp:20,eff:{status:"psn",statusChance:30},desc:"A venomous jab."},
"cross-poison":{id:"cross-poison",name:"Cross Poison",type:"Poison",cat:"phys",pow:70,acc:100,pp:20,eff:{status:"psn",statusChance:10},desc:"A toxic cross slash."},
"sludge-bomb":{id:"sludge-bomb",name:"Sludge Bomb",type:"Poison",cat:"spec",pow:90,acc:100,pp:10,eff:{status:"psn",statusChance:30},desc:"Hurls toxic sludge."},
"malignant-chain":{id:"malignant-chain",name:"Malignant Chain",type:"Poison",cat:"spec",pow:100,acc:100,pp:5,eff:{status:"psn",statusChance:50},desc:"Pecharunt's toxic chains."},
earthquake:{id:"earthquake",name:"Earthquake",type:"Ground",cat:"phys",pow:100,acc:100,pp:10,eff:{},desc:"Shakes the whole arena."},
"drill-run":{id:"drill-run",name:"Drill Run",type:"Ground",cat:"phys",pow:80,acc:95,pp:10,eff:{},desc:"A spinning drill charge."},
"precipice-blades":{id:"precipice-blades",name:"Precipice Blades",type:"Ground",cat:"phys",pow:120,acc:85,pp:10,eff:{},desc:"Groudon's erupting blades."},
"thousand-arrows":{id:"thousand-arrows",name:"Thousand Arrows",type:"Ground",cat:"phys",pow:90,acc:100,pp:10,eff:{},desc:"Zygarde's piercing volley."},
"earth-power":{id:"earth-power",name:"Earth Power",type:"Ground",cat:"spec",pow:90,acc:100,pp:10,eff:{foeStat:{spd:-1}},desc:"Ground erupts under the foe."},
"rock-throw":{id:"rock-throw",name:"Rock Throw",type:"Rock",cat:"phys",pow:50,acc:90,pp:15,eff:{},desc:"Hurls a rock."},
"rock-slide":{id:"rock-slide",name:"Rock Slide",type:"Rock",cat:"phys",pow:75,acc:90,pp:10,eff:{flinch:30},desc:"An avalanche that may flinch."},
"stone-edge":{id:"stone-edge",name:"Stone Edge",type:"Rock",cat:"phys",pow:100,acc:80,pp:5,eff:{},desc:"Jagged stones."},
"rock-blast":{id:"rock-blast",name:"Rock Blast",type:"Rock",cat:"phys",pow:25,acc:90,pp:10,eff:{hits:[2,5]},desc:"Hurls rocks 2-5 times."},
"diamond-storm":{id:"diamond-storm",name:"Diamond Storm",type:"Rock",cat:"phys",pow:100,acc:95,pp:5,eff:{stat:{def:1}},desc:"Diancie's glittering storm."},
"power-gem":{id:"power-gem",name:"Power Gem",type:"Rock",cat:"spec",pow:80,acc:100,pp:20,eff:{},desc:"A gemstone beam."},
"ancient-power":{id:"ancient-power",name:"Ancient Power",type:"Rock",cat:"spec",pow:60,acc:100,pp:5,eff:{stat:{atk:1,def:1,spa:1,spd:1,spe:1}},desc:"Primordial energy surge."},
"bug-bite":{id:"bug-bite",name:"Bug Bite",type:"Bug",cat:"phys",pow:60,acc:100,pp:20,eff:{},desc:"A crunchy bite."},
"x-scissor":{id:"x-scissor",name:"X-Scissor",type:"Bug",cat:"phys",pow:80,acc:100,pp:15,eff:{},desc:"A crossing slash."},
"bug-buzz":{id:"bug-buzz",name:"Bug Buzz",type:"Bug",cat:"spec",pow:90,acc:100,pp:10,eff:{foeStat:{spd:-1}},desc:"A vibrating screech."},
"shadow-claw":{id:"shadow-claw",name:"Shadow Claw",type:"Ghost",cat:"phys",pow:70,acc:100,pp:15,eff:{},desc:"A claw of darkness."},
"shadow-force":{id:"shadow-force",name:"Shadow Force",type:"Ghost",cat:"phys",pow:120,acc:100,pp:5,eff:{},desc:"Giratina's strike from the void."},
"spectral-thief":{id:"spectral-thief",name:"Spectral Thief",type:"Ghost",cat:"phys",pow:90,acc:100,pp:10,eff:{},desc:"Marshadow's soul steal."},
"shadow-ball":{id:"shadow-ball",name:"Shadow Ball",type:"Ghost",cat:"spec",pow:80,acc:100,pp:15,eff:{foeStat:{spd:-1}},desc:"A dark orb."},
hex:{id:"hex",name:"Hex",type:"Ghost",cat:"spec",pow:65,acc:100,pp:10,eff:{},desc:"A spiteful curse."},
"moongeist-beam":{id:"moongeist-beam",name:"Moongeist Beam",type:"Ghost",cat:"spec",pow:100,acc:100,pp:5,eff:{},desc:"Lunala's piercing moonbeam."},
"astral-barrage":{id:"astral-barrage",name:"Astral Barrage",type:"Ghost",cat:"spec",pow:120,acc:100,pp:5,eff:{},desc:"Calyrex's starfall."},
bite:{id:"bite",name:"Bite",type:"Dark",cat:"phys",pow:60,acc:100,pp:25,eff:{flinch:30},desc:"May cause flinching."},
crunch:{id:"crunch",name:"Crunch",type:"Dark",cat:"phys",pow:80,acc:100,pp:15,eff:{foeStat:{def:-1}},desc:"Crushes with fangs."},
"night-slash":{id:"night-slash",name:"Night Slash",type:"Dark",cat:"phys",pow:70,acc:100,pp:15,eff:{},desc:"A midnight slash."},
"sucker-punch":{id:"sucker-punch",name:"Sucker Punch",type:"Dark",cat:"phys",pow:70,acc:100,pp:5,eff:{priority:1},desc:"Strikes first, dirty."},
"wicked-blow":{id:"wicked-blow",name:"Wicked Blow",type:"Dark",cat:"phys",pow:75,acc:100,pp:10,eff:{},desc:"Urshifu's ruthless blow."},
"dark-pulse":{id:"dark-pulse",name:"Dark Pulse",type:"Dark",cat:"spec",pow:80,acc:100,pp:15,eff:{flinch:20},desc:"A dark shockwave."},
"bullet-punch":{id:"bullet-punch",name:"Bullet Punch",type:"Steel",cat:"phys",pow:40,acc:100,pp:30,eff:{priority:1},desc:"A piston-fast punch."},
"iron-head":{id:"iron-head",name:"Iron Head",type:"Steel",cat:"phys",pow:80,acc:100,pp:15,eff:{flinch:30},desc:"A steel skull slam."},
"iron-tail":{id:"iron-tail",name:"Iron Tail",type:"Steel",cat:"phys",pow:100,acc:75,pp:15,eff:{foeStat:{def:-1}},desc:"A heavy steel tail."},
"sunsteel-strike":{id:"sunsteel-strike",name:"Sunsteel Strike",type:"Steel",cat:"phys",pow:100,acc:100,pp:5,eff:{},desc:"Solgaleo's meteor charge."},
"behemoth-blade":{id:"behemoth-blade",name:"Behemoth Blade",type:"Steel",cat:"phys",pow:100,acc:100,pp:5,eff:{},desc:"Zacian's royal slash."},
"behemoth-bash":{id:"behemoth-bash",name:"Behemoth Bash",type:"Steel",cat:"phys",pow:100,acc:100,pp:5,eff:{},desc:"Zamazenta's shield charge."},
"searing-sunraze-smash":{id:"searing-sunraze-smash",name:"Searing Sunraze Smash",type:"Steel",cat:"phys",pow:200,acc:100,pp:5,eff:{},desc:"Solgaleo's Z-Power supernova."},
"flash-cannon":{id:"flash-cannon",name:"Flash Cannon",type:"Steel",cat:"spec",pow:80,acc:100,pp:10,eff:{foeStat:{spd:-1}},desc:"A light-speed beam."},
"doom-desire":{id:"doom-desire",name:"Doom Desire",type:"Steel",cat:"spec",pow:140,acc:100,pp:5,eff:{},desc:"Jirachi's delayed starfall."},
"fire-punch":{id:"fire-punch",name:"Fire Punch",type:"Fire",cat:"phys",pow:75,acc:100,pp:15,eff:{status:"brn",statusChance:10},desc:"A burning punch."},
"blaze-kick":{id:"blaze-kick",name:"Blaze Kick",type:"Fire",cat:"phys",pow:85,acc:90,pp:10,eff:{status:"brn",statusChance:10},desc:"A blazing kick."},
"flare-blitz":{id:"flare-blitz",name:"Flare Blitz",type:"Fire",cat:"phys",pow:120,acc:100,pp:15,eff:{recoil:0.33,status:"brn",statusChance:10},desc:"A fiery suicide charge."},
"sacred-fire":{id:"sacred-fire",name:"Sacred Fire",type:"Fire",cat:"phys",pow:100,acc:95,pp:5,eff:{status:"brn",statusChance:50},desc:"Ho-Oh's holy flame."},
"v-create":{id:"v-create",name:"V-create",type:"Fire",cat:"phys",pow:180,acc:95,pp:5,eff:{stat:{def:-1,spd:-1,spe:-1}},desc:"Victini's ultimate blaze."},
ember:{id:"ember",name:"Ember",type:"Fire",cat:"spec",pow:40,acc:100,pp:25,eff:{status:"brn",statusChance:10},desc:"Small flames."},
flamethrower:{id:"flamethrower",name:"Flamethrower",type:"Fire",cat:"spec",pow:90,acc:100,pp:15,eff:{status:"brn",statusChance:10},desc:"A torrent of fire."},
"fire-blast":{id:"fire-blast",name:"Fire Blast",type:"Fire",cat:"spec",pow:110,acc:85,pp:5,eff:{status:"brn",statusChance:10},desc:"A star-shaped inferno."},
"blue-flare":{id:"blue-flare",name:"Blue Flare",type:"Fire",cat:"spec",pow:130,acc:85,pp:5,eff:{status:"brn",statusChance:20},desc:"Reshiram's azure flame."},
"fusion-flare":{id:"fusion-flare",name:"Fusion Flare",type:"Fire",cat:"spec",pow:100,acc:100,pp:5,eff:{},desc:"Reshiram's fusion flame."},
waterfall:{id:"waterfall",name:"Waterfall",type:"Water",cat:"phys",pow:80,acc:100,pp:15,eff:{flinch:20},desc:"Charges like a cascade."},
"aqua-tail":{id:"aqua-tail",name:"Aqua Tail",type:"Water",cat:"phys",pow:90,acc:90,pp:10,eff:{},desc:"A whipping water tail."},
"surging-strikes":{id:"surging-strikes",name:"Surging Strikes",type:"Water",cat:"phys",pow:75,acc:100,pp:5,eff:{hits:[3,3]},desc:"Urshifu's triple surge."},
"water-gun":{id:"water-gun",name:"Water Gun",type:"Water",cat:"spec",pow:40,acc:100,pp:25,eff:{},desc:"A pressurized squirt."},
"bubble-beam":{id:"bubble-beam",name:"Bubble Beam",type:"Water",cat:"spec",pow:65,acc:100,pp:20,eff:{foeStat:{spe:-1}},desc:"Slowing bubbles."},
surf:{id:"surf",name:"Surf",type:"Water",cat:"spec",pow:90,acc:100,pp:15,eff:{},desc:"A huge wave."},
"hydro-pump":{id:"hydro-pump",name:"Hydro Pump",type:"Water",cat:"spec",pow:110,acc:80,pp:5,eff:{},desc:"A violent water cannon."},
"origin-pulse":{id:"origin-pulse",name:"Origin Pulse",type:"Water",cat:"spec",pow:110,acc:85,pp:10,eff:{},desc:"Kyogre's primal deluge."},
"steam-eruption":{id:"steam-eruption",name:"Steam Eruption",type:"Water",cat:"spec",pow:110,acc:95,pp:5,eff:{status:"brn",statusChance:30},desc:"Volcanion's scalding steam."},
"thunder-punch":{id:"thunder-punch",name:"Thunder Punch",type:"Electric",cat:"phys",pow:75,acc:100,pp:15,eff:{status:"par",statusChance:10},desc:"An electrified punch."},
"wild-charge":{id:"wild-charge",name:"Wild Charge",type:"Electric",cat:"phys",pow:90,acc:100,pp:15,eff:{recoil:0.25},desc:"A reckless electric tackle."},
"fusion-bolt":{id:"fusion-bolt",name:"Fusion Bolt",type:"Electric",cat:"phys",pow:100,acc:100,pp:5,eff:{},desc:"Zekrom's fusion bolt."},
"thunder-shock":{id:"thunder-shock",name:"Thunder Shock",type:"Electric",cat:"spec",pow:40,acc:100,pp:30,eff:{status:"par",statusChance:10},desc:"A weak jolt."},
thunderbolt:{id:"thunderbolt",name:"Thunderbolt",type:"Electric",cat:"spec",pow:90,acc:100,pp:15,eff:{status:"par",statusChance:10},desc:"A strong electric blast."},
thunder:{id:"thunder",name:"Thunder",type:"Electric",cat:"spec",pow:110,acc:70,pp:10,eff:{status:"par",statusChance:30},desc:"A thunderbolt from the sky."},
"electro-drift":{id:"electro-drift",name:"Electro Drift",type:"Electric",cat:"spec",pow:100,acc:100,pp:5,eff:{},desc:"Miraidon's racing surge."},
"bolt-strike":{id:"bolt-strike",name:"Bolt Strike",type:"Electric",cat:"phys",pow:130,acc:85,pp:5,eff:{status:"par",statusChance:20},desc:"Zekrom's lightning charge."},
"vine-whip":{id:"vine-whip",name:"Vine Whip",type:"Grass",cat:"phys",pow:45,acc:100,pp:25,eff:{},desc:"Lashes with vines."},
"razor-leaf":{id:"razor-leaf",name:"Razor Leaf",type:"Grass",cat:"phys",pow:55,acc:95,pp:25,eff:{},desc:"Sharp leaves."},
"seed-bomb":{id:"seed-bomb",name:"Seed Bomb",type:"Grass",cat:"phys",pow:80,acc:100,pp:15,eff:{},desc:"Explosive seeds."},
"leaf-blade":{id:"leaf-blade",name:"Leaf Blade",type:"Grass",cat:"phys",pow:90,acc:100,pp:15,eff:{},desc:"A leaf katana."},
"ivy-cudgel":{id:"ivy-cudgel",name:"Ivy Cudgel",type:"Grass",cat:"phys",pow:100,acc:100,pp:10,eff:{},desc:"Ogerpon's thorny club."},
"energy-ball":{id:"energy-ball",name:"Energy Ball",type:"Grass",cat:"spec",pow:90,acc:100,pp:10,eff:{foeStat:{spd:-1}},desc:"A nature orb."},
"solar-beam":{id:"solar-beam",name:"Solar Beam",type:"Grass",cat:"spec",pow:120,acc:100,pp:10,eff:{},desc:"Absorbs light, then fires."},
"ice-punch":{id:"ice-punch",name:"Ice Punch",type:"Ice",cat:"phys",pow:75,acc:100,pp:15,eff:{status:"frz",statusChance:10},desc:"A freezing punch."},
"icicle-spear":{id:"icicle-spear",name:"Icicle Spear",type:"Ice",cat:"phys",pow:25,acc:100,pp:30,eff:{hits:[2,5]},desc:"Hurls icicles 2-5 times."},
"glacial-lance":{id:"glacial-lance",name:"Glacial Lance",type:"Ice",cat:"phys",pow:130,acc:100,pp:5,eff:{},desc:"Glastrier's ice joust."},
"icy-wind":{id:"icy-wind",name:"Icy Wind",type:"Ice",cat:"spec",pow:55,acc:95,pp:15,eff:{foeStat:{spe:-1}},desc:"Chilling wind."},
"ice-beam":{id:"ice-beam",name:"Ice Beam",type:"Ice",cat:"spec",pow:90,acc:100,pp:10,eff:{status:"frz",statusChance:10},desc:"A freezing beam."},
blizzard:{id:"blizzard",name:"Blizzard",type:"Ice",cat:"spec",pow:110,acc:70,pp:5,eff:{status:"frz",statusChance:10},desc:"A howling blizzard."},
"zen-headbutt":{id:"zen-headbutt",name:"Zen Headbutt",type:"Psychic",cat:"phys",pow:80,acc:90,pp:15,eff:{flinch:20},desc:"A focused headbutt."},
psybeam:{id:"psybeam",name:"Psybeam",type:"Psychic",cat:"spec",pow:65,acc:100,pp:20,eff:{},desc:"A psychic ray."},
psychic:{id:"psychic",name:"Psychic",type:"Psychic",cat:"spec",pow:90,acc:100,pp:10,eff:{foeStat:{spd:-1}},desc:"A powerful telekinetic blast."},
"psycho-boost":{id:"psycho-boost",name:"Psycho Boost",type:"Psychic",cat:"spec",pow:140,acc:90,pp:5,eff:{stat:{spa:-2}},desc:"Deoxys's psychic nova."},
"genesis-supernova":{id:"genesis-supernova",name:"Genesis Supernova",type:"Psychic",cat:"spec",pow:160,acc:90,pp:5,eff:{},desc:"Mew's big-bang blast."},
"light-that-burns-the-sky":{id:"light-that-burns-the-sky",name:"Light That Burns the Sky",type:"Psychic",cat:"spec",pow:200,acc:100,pp:5,eff:{},desc:"Necrozma's prismatic judgment."},
"photon-geyser":{id:"photon-geyser",name:"Photon Geyser",type:"Psychic",cat:"spec",pow:100,acc:100,pp:5,eff:{},desc:"Necrozma's light pillar."},
"hyperspace-hole":{id:"hyperspace-hole",name:"Hyperspace Hole",type:"Psychic",cat:"spec",pow:80,acc:100,pp:5,eff:{},desc:"Hoopa's warp strike."},
"dragon-claw":{id:"dragon-claw",name:"Dragon Claw",type:"Dragon",cat:"phys",pow:80,acc:100,pp:15,eff:{},desc:"Dragon talons."},
outrage:{id:"outrage",name:"Outrage",type:"Dragon",cat:"phys",pow:120,acc:100,pp:10,eff:{},desc:"A draconic rampage."},
"dragon-pulse":{id:"dragon-pulse",name:"Dragon Pulse",type:"Dragon",cat:"spec",pow:85,acc:100,pp:10,eff:{},desc:"A draconic shockwave."},
"draco-meteor":{id:"draco-meteor",name:"Draco Meteor",type:"Dragon",cat:"spec",pow:130,acc:90,pp:5,eff:{stat:{spa:-2}},desc:"Calls down meteors."},
"spacial-rend":{id:"spacial-rend",name:"Spacial Rend",type:"Dragon",cat:"spec",pow:100,acc:95,pp:5,eff:{},desc:"Palkia tears space itself."},
"roar-of-time":{id:"roar-of-time",name:"Roar of Time",type:"Dragon",cat:"spec",pow:150,acc:90,pp:5,eff:{},desc:"Dialga's temporal roar."},
"core-enforcer":{id:"core-enforcer",name:"Core Enforcer",type:"Dragon",cat:"spec",pow:100,acc:100,pp:10,eff:{},desc:"Zygarde's core beam."},
eternabeam:{id:"eternabeam",name:"Eternabeam",type:"Dragon",cat:"spec",pow:160,acc:90,pp:5,eff:{},desc:"Eternatus's endless ray."},
"play-rough":{id:"play-rough",name:"Play Rough",type:"Fairy",cat:"phys",pow:90,acc:90,pp:10,eff:{foeStat:{atk:-1}},desc:"Roughhousing magic."},
"dazzling-gleam":{id:"dazzling-gleam",name:"Dazzling Gleam",type:"Fairy",cat:"spec",pow:80,acc:100,pp:10,eff:{},desc:"A blinding flash."},
moonblast:{id:"moonblast",name:"Moonblast",type:"Fairy",cat:"spec",pow:95,acc:100,pp:15,eff:{foeStat:{spa:-1}},desc:"A moonlit blast."},
"draining-kiss":{id:"draining-kiss",name:"Draining Kiss",type:"Fairy",cat:"spec",pow:50,acc:100,pp:10,eff:{drain:0.75},desc:"Steals vitality."},
"fleur-cannon":{id:"fleur-cannon",name:"Fleur Cannon",type:"Fairy",cat:"spec",pow:130,acc:90,pp:5,eff:{stat:{spa:-2}},desc:"Magearna's floral cannon."},
judgment:{id:"judgment",name:"Judgment",type:"Normal",cat:"spec",pow:100,acc:100,pp:10,eff:{},desc:"Arceus's divine verdict."},
"relic-song":{id:"relic-song",name:"Relic Song",type:"Normal",cat:"spec",pow:75,acc:100,pp:10,eff:{status:"slp",statusChance:10},desc:"Meloetta's ancient melody."},
"techno-blast":{id:"techno-blast",name:"Techno Blast",type:"Normal",cat:"spec",pow:120,acc:100,pp:5,eff:{},desc:"Genesect's cannon fire."},
growl:{id:"growl",name:"Growl",type:"Normal",cat:"status",pow:0,acc:100,pp:40,eff:{foeStat:{atk:-1}},desc:"Lowers the foe's Attack."},
"tail-whip":{id:"tail-whip",name:"Tail Whip",type:"Normal",cat:"status",pow:0,acc:100,pp:30,eff:{foeStat:{def:-1}},desc:"Lowers the foe's Defense."},
leer:{id:"leer",name:"Leer",type:"Normal",cat:"status",pow:0,acc:100,pp:30,eff:{foeStat:{def:-1}},desc:"A menacing glare."},
"swords-dance":{id:"swords-dance",name:"Swords Dance",type:"Normal",cat:"status",pow:0,acc:100,pp:20,eff:{stat:{atk:2}},desc:"Sharply raises Attack."},
"nasty-plot":{id:"nasty-plot",name:"Nasty Plot",type:"Dark",cat:"status",pow:0,acc:100,pp:20,eff:{stat:{spa:2}},desc:"Sharply raises Sp. Atk."},
"bulk-up":{id:"bulk-up",name:"Bulk Up",type:"Fighting",cat:"status",pow:0,acc:100,pp:20,eff:{stat:{atk:1,def:1}},desc:"Raises Attack and Defense."},
"calm-mind":{id:"calm-mind",name:"Calm Mind",type:"Psychic",cat:"status",pow:0,acc:100,pp:20,eff:{stat:{spa:1,spd:1}},desc:"Raises Sp. Atk and Sp. Def."},
agility:{id:"agility",name:"Agility",type:"Psychic",cat:"status",pow:0,acc:100,pp:30,eff:{stat:{spe:2}},desc:"Sharply raises Speed."},
"iron-defense":{id:"iron-defense",name:"Iron Defense",type:"Steel",cat:"status",pow:0,acc:100,pp:15,eff:{stat:{def:2}},desc:"Sharply raises Defense."},
amnesia:{id:"amnesia",name:"Amnesia",type:"Psychic",cat:"status",pow:0,acc:100,pp:20,eff:{stat:{spd:2}},desc:"Sharply raises Sp. Def."},
"quiver-dance":{id:"quiver-dance",name:"Quiver Dance",type:"Bug",cat:"status",pow:0,acc:100,pp:20,eff:{stat:{spa:1,spd:1,spe:1}},desc:"A mystical dance."},
"dragon-dance":{id:"dragon-dance",name:"Dragon Dance",type:"Dragon",cat:"status",pow:0,acc:100,pp:20,eff:{stat:{atk:1,spe:1}},desc:"An ancient draconic dance."},
"work-up":{id:"work-up",name:"Work Up",type:"Normal",cat:"status",pow:0,acc:100,pp:30,eff:{stat:{atk:1,spa:1}},desc:"Psyche yourself up."},
growth:{id:"growth",name:"Growth",type:"Normal",cat:"status",pow:0,acc:100,pp:20,eff:{stat:{spa:1}},desc:"Grows stronger."},
"cosmic-power":{id:"cosmic-power",name:"Cosmic Power",type:"Psychic",cat:"status",pow:0,acc:100,pp:20,eff:{stat:{def:1,spd:1}},desc:"Draws power from the cosmos."},
"thunder-wave":{id:"thunder-wave",name:"Thunder Wave",type:"Electric",cat:"status",pow:0,acc:90,pp:20,eff:{status:"par"},desc:"Paralyzes the foe."},
"sleep-powder":{id:"sleep-powder",name:"Sleep Powder",type:"Grass",cat:"status",pow:0,acc:75,pp:15,eff:{status:"slp"},desc:"Puts the foe to sleep."},
"stun-spore":{id:"stun-spore",name:"Stun Spore",type:"Grass",cat:"status",pow:0,acc:75,pp:30,eff:{status:"par"},desc:"Paralyzing spores."},
"poison-powder":{id:"poison-powder",name:"Poison Powder",type:"Poison",cat:"status",pow:0,acc:75,pp:35,eff:{status:"psn"},desc:"Poisonous powder."},
toxic:{id:"toxic",name:"Toxic",type:"Poison",cat:"status",pow:0,acc:90,pp:10,eff:{status:"psn"},desc:"Badly poisons the foe."},
sing:{id:"sing",name:"Sing",type:"Normal",cat:"status",pow:0,acc:55,pp:15,eff:{status:"slp"},desc:"A soothing lullaby."},
hypnosis:{id:"hypnosis",name:"Hypnosis",type:"Psychic",cat:"status",pow:0,acc:60,pp:20,eff:{status:"slp"},desc:"Hypnotic suggestion."},
"will-o-wisp":{id:"will-o-wisp",name:"Will-O-Wisp",type:"Fire",cat:"status",pow:0,acc:85,pp:15,eff:{status:"brn"},desc:"Burns the foe with ghostly fire."},
recover:{id:"recover",name:"Recover",type:"Normal",cat:"status",pow:0,acc:100,pp:10,eff:{heal:0.5},desc:"Restores half of max HP."},
rest:{id:"rest",name:"Rest",type:"Psychic",cat:"status",pow:0,acc:100,pp:10,eff:{heal:1,status:"slp"},desc:"Fully heals, then sleeps."},
protect:{id:"protect",name:"Protect",type:"Normal",cat:"status",pow:0,acc:100,pp:10,eff:{priority:4},desc:"Blocks damage this turn."},
"light-screen":{id:"light-screen",name:"Light Screen",type:"Psychic",cat:"status",pow:0,acc:100,pp:30,eff:{stat:{spd:1}},desc:"A shimmering psychic barrier."},
reflect:{id:"reflect",name:"Reflect",type:"Psychic",cat:"status",pow:0,acc:100,pp:20,eff:{stat:{def:1}},desc:"A reflective psychic wall."},
/* ---- anime signature moves ---- */
kamehameha:{id:"kamehameha",name:"Kamehameha",type:"Fighting",cat:"spec",pow:95,acc:100,pp:10,eff:{},desc:"Goku's legendary energy wave. KAAA-MEEE!"},
"spirit-bomb":{id:"spirit-bomb",name:"Spirit Bomb",type:"Fighting",cat:"spec",pow:120,acc:85,pp:5,eff:{},desc:"Energy borrowed from all living things."},
rasengan:{id:"rasengan",name:"Rasengan",type:"Fighting",cat:"phys",pow:90,acc:100,pp:10,eff:{},desc:"Naruto's spinning chakra sphere."},
chidori:{id:"chidori",name:"Chidori",type:"Electric",cat:"phys",pow:95,acc:100,pp:10,eff:{status:"par",statusChance:10},desc:"A blade of crackling lightning."},
"hollow-purple":{id:"hollow-purple",name:"Hollow Purple",type:"Psychic",cat:"spec",pow:130,acc:90,pp:5,eff:{},desc:"Gojo's imaginary mass erasure."},
"domain-expansion":{id:"domain-expansion",name:"Domain Expansion",type:"Psychic",cat:"spec",pow:140,acc:90,pp:5,eff:{foeStat:{spd:-1}},desc:"An inescapable sure-hit domain."},
"bajrang-gun":{id:"bajrang-gun",name:"Gear Fifth: Bajrang Gun",type:"Fighting",cat:"phys",pow:150,acc:90,pp:5,eff:{},desc:"Luffy's giant cartoon fist of freedom."},
"getsuga-tensho":{id:"getsuga-tensho",name:"Getsuga Tensho",type:"Ghost",cat:"spec",pow:100,acc:100,pp:10,eff:{},desc:"Ichigo's moon-fang spirit slash."},
"one-punch":{id:"one-punch",name:"One Punch",type:"Fighting",cat:"phys",pow:200,acc:90,pp:5,eff:{},desc:"Saitama ends it. Obviously."},
"detroit-smash":{id:"detroit-smash",name:"Detroit Smash",type:"Fighting",cat:"phys",pow:110,acc:90,pp:10,eff:{},desc:"Deku's full-power smash."},
"hinokami-kagura":{id:"hinokami-kagura",name:"Hinokami Kagura",type:"Fire",cat:"phys",pow:100,acc:100,pp:10,eff:{status:"brn",statusChance:10},desc:"Tanjiro's dance of the fire god."},
"infinity-guard":{id:"infinity-guard",name:"Infinity Guard",type:"Psychic",cat:"status",pow:0,acc:100,pp:10,eff:{priority:4},desc:"Gojo's Infinity. Nothing touches him."}
};

/* ---------------- ITEMS ---------------- */
G.Data.ITEMS = {
"poke-ball":{id:"poke-ball",name:"Poké Ball",desc:"Catches wild Pokémon.",price:200,kind:"ball",ball:1},
"great-ball":{id:"great-ball",name:"Great Ball",desc:"Better catch rate.",price:600,kind:"ball",ball:1.5},
"ultra-ball":{id:"ultra-ball",name:"Ultra Ball",desc:"Great catch rate.",price:1200,kind:"ball",ball:2},
"master-ball":{id:"master-ball",name:"Master Ball",desc:"Catches anything, guaranteed.",price:0,kind:"ball",ball:255},
potion:{id:"potion",name:"Potion",desc:"Restores 20 HP.",price:300,kind:"heal",heal:20},
"super-potion":{id:"super-potion",name:"Super Potion",desc:"Restores 50 HP.",price:700,kind:"heal",heal:50},
"hyper-potion":{id:"hyper-potion",name:"Hyper Potion",desc:"Restores 120 HP.",price:1200,kind:"heal",heal:120},
"max-potion":{id:"max-potion",name:"Max Potion",desc:"Fully restores HP.",price:2500,kind:"heal",heal:9999},
revive:{id:"revive",name:"Revive",desc:"Revives a fainted Pokémon at half HP.",price:1500,kind:"heal",revive:0.5},
"full-heal":{id:"full-heal",name:"Full Heal",desc:"Cures all status conditions.",price:600,kind:"heal",cure:true},
antidote:{id:"antidote",name:"Antidote",desc:"Cures poison.",price:100,kind:"heal",cureStatus:"psn"},
"paralyze-heal":{id:"paralyze-heal",name:"Paralyze Heal",desc:"Cures paralysis.",price:200,kind:"heal",cureStatus:"par"},
awakening:{id:"awakening",name:"Awakening",desc:"Wakes a sleeping Pokémon.",price:250,kind:"heal",cureStatus:"slp"},
"burn-heal":{id:"burn-heal",name:"Burn Heal",desc:"Cures a burn.",price:250,kind:"heal",cureStatus:"brn"},
"ice-heal":{id:"ice-heal",name:"Ice Heal",desc:"Thaws a frozen Pokémon.",price:250,kind:"heal",cureStatus:"frz"},
"rare-candy":{id:"rare-candy",name:"Rare Candy",desc:"Raises a Pokémon by one level.",price:4800,kind:"heal",rareCandy:true},
"fire-stone":{id:"fire-stone",name:"Fire Stone",desc:"Evolves certain Pokémon.",price:2100,kind:"evo"},
"water-stone":{id:"water-stone",name:"Water Stone",desc:"Evolves certain Pokémon.",price:2100,kind:"evo"},
"thunder-stone":{id:"thunder-stone",name:"Thunder Stone",desc:"Evolves certain Pokémon.",price:2100,kind:"evo"},
"leaf-stone":{id:"leaf-stone",name:"Leaf Stone",desc:"Evolves certain Pokémon.",price:2100,kind:"evo"},
"moon-stone":{id:"moon-stone",name:"Moon Stone",desc:"Evolves certain Pokémon.",price:2100,kind:"evo"},
"sun-stone":{id:"sun-stone",name:"Sun Stone",desc:"Evolves certain Pokémon.",price:2100,kind:"evo"},
"dna-splicers":{id:"dna-splicers",name:"DNA Splicers",desc:"Fuse two Pokémon at the Fusion Lab.",price:0,kind:"key"},
"umbral-shard":{id:"umbral-shard",name:"Umbral Shard",desc:"A fragment of Team UMBRA's dark plan.",price:0,kind:"key"},
"seal-1":{id:"seal-1",name:"Umbral Seal I",desc:"First seal. It hums with wrongness.",price:0,kind:"key"},
"seal-2":{id:"seal-2",name:"Umbral Seal II",desc:"Second seal. Cold to the touch.",price:0,kind:"key"},
"seal-3":{id:"seal-3",name:"Umbral Seal III",desc:"Third seal. It whispers.",price:0,kind:"key"},
"rift-key":{id:"rift-key",name:"Rift Key",desc:"Opens the Distortion Rift Den.",price:0,kind:"key"},
"x-attack":{id:"x-attack",name:"X Attack",desc:"Sharply boosts Attack in battle.",price:500,kind:"battle",battleStat:{atk:2}},
"x-defense":{id:"x-defense",name:"X Defense",desc:"Sharply boosts Defense in battle.",price:550,kind:"battle",battleStat:{def:2}},
"x-speed":{id:"x-speed",name:"X Speed",desc:"Sharply boosts Speed in battle.",price:350,kind:"battle",battleStat:{spe:2}},
"x-spatk":{id:"x-spatk",name:"X Sp. Atk",desc:"Sharply boosts Sp. Atk in battle.",price:350,kind:"battle",battleStat:{spa:2}}
};

/* ---------------- SPECIES ---------------- */
G.Data.SPECIES = {};
