/* Pokémon: Distortion Rift — maps, trainers, encounters.
   Tile legend: # wall/building  . path  , grass  ~ water  D door  = road
                * flower  s sand  T tree  o rock  (space) void. All blocked except . , * s = */
window.G = window.G || {};
G.Maps = G.Maps || {};

/* ============ TRAINER REGISTRY ============
   Story scripts battle these by id: {battle:{trainer:"gym1"}}.
   echo1..echo5 have party:null + echoStage: engine resolves via G.AI.echoParty(stage). */
G.Maps.TRAINERS = {
echo1:{name:"ECHO",sprite:"rival",reward:150,ai:"echo",echoStage:1,party:null,
 intro:["...My NEXUS doesn't make mistakes. Prove it wrong!"],
 outro:["...Lucky. NEXUS, log this: rematch scheduled."]},
echo2:{name:"ECHO",sprite:"rival",reward:400,ai:"echo",echoStage:2,party:null,
 intro:["NEXUS analyzed your last twelve battles. I know your lead. I know your habits.","Let's see if knowing is enough."],
 outro:["You adapt fast. Annoying. Useful. Noted."]},
echo3:{name:"ECHO",sprite:"rival",reward:800,ai:"echo",echoStage:3,party:null,
 intro:["Three badges. Not bad. I've been training between your battles — NEXUS feeds me your replays.","No more free wins, rival."],
 outro:["...You switched exactly when I wouldn't. I'll remember that."]},
echo4:{name:"ECHO",sprite:"rival",reward:1500,ai:"echo",echoStage:4,party:null,
 intro:["Victory Road. One of us walks out a contender.","I've counter-teamed your entire playstyle. Show me something new."],
 outro:["Fine. FINE. You're the real deal. Don't lose to SERAPHINA — I want my rematch."]},
echo5:{name:"ECHO",sprite:"rival",reward:3000,ai:"echo",echoStage:5,party:null,
 intro:["The League finals warm-up. Just us, like the old days behind the lab.","NEXUS, full analysis mode. No holding back — either of us."],
 outro:["...That was the best battle of my life. Go take the crown. I'll be right behind you."]},
gym1:{name:"VOLTA",sprite:"leader",reward:1500,ai:"basic",party:[{sp:"electrike",lvl:13},{sp:"flaaffy",lvl:14},{sp:"manectric",lvl:16}],
 intro:["Yo! Welcome to the VOLT GYM! I'm VOLTA — fastest leader in the region!","My team hits like a thunderstorm. Grounded? You will be!"],
 outro:["Zapped... You short-circuited my whole strategy! Take the VOLT BADGE!"]},
gym2:{name:"FERN",sprite:"leader",reward:1800,ai:"basic",party:[{sp:"shroomish",lvl:19},{sp:"ivysaur",lvl:21},{sp:"breloom",lvl:23}],
 intro:["Shhh... the gym is a garden. I'm FERN. We grow strong quietly here.","Let's see if your fire burns brighter than my roots."],
 outro:["...Well cultivated. The FERN BADGE is yours. Grow well, trainer."]},
gym3:{name:"MARINA",sprite:"leader",reward:2200,ai:"basic",party:[{sp:"wartortle",lvl:27},{sp:"gyarados",lvl:29},{sp:"blastoise",lvl:31}],
 intro:["Ahoy! MARINA of the HARBOR GYM! The tide favors the bold, sailor!","My crew's been through storms you'd cry about. Dive in!"],
 outro:["Blub... blown out to sea! Take the HARBOR BADGE — you earned it, captain!"]},
gym4:{name:"DRAKE",sprite:"leader",reward:2800,ai:"basic",party:[{sp:"vibrava",lvl:34},{sp:"dragonair",lvl:36},{sp:"flygon",lvl:38},{sp:"salamence",lvl:40}],
 intro:["I am DRAKE. Dragons bow to no one — and neither do I.","Four badges got you here. My dragons will see if you deserve the League."],
 outro:["...Magnificent. The DRAKE BADGE is yours. The League awaits — and so does destiny."]},
"e4-kaia":{name:"KAIA",sprite:"elite",reward:4000,ai:"boss",party:[{sp:"lucario",lvl:47},{sp:"machamp",lvl:48},{sp:"breloom",lvl:48},{sp:"machoke",lvl:46}],
 intro:["ELITE FOUR KAIA. I broke three mountains training. You'll be the fourth.","No tricks. No mercy. Just fists."],
 outro:["...My fists acknowledge you. Pass, warrior."]},
"e4-mortis":{name:"MORTIS",sprite:"elite",reward:4000,ai:"boss",party:[{sp:"gengar",lvl:48},{sp:"umbreon",lvl:48},{sp:"houndoom",lvl:47},{sp:"absol",lvl:48}],
 intro:["ELITE FOUR MORTIS. The dead whisper your name, little trainer.","They say you'll fall here. Let's ask them together."],
 outro:["The whispers... congratulate you. Go. The dark parts for you."]},
"e4-ferro":{name:"FERRO",sprite:"elite",reward:4000,ai:"boss",party:[{sp:"metagross",lvl:49},{sp:"scizor",lvl:48},{sp:"aggron",lvl:47},{sp:"lucario",lvl:47}],
 intro:["ELITE FOUR FERRO. Steel does not bend. Steel does not break.","Test yourself against the unbreakable."],
 outro:["...A crack. In MY defense. Remarkable. Proceed."]},
"e4-sage":{name:"SAGE",sprite:"elite",reward:4000,ai:"boss",party:[{sp:"alakazam",lvl:49},{sp:"espeon",lvl:48},{sp:"gardevoir",lvl:48},{sp:"metagross",lvl:47}],
 intro:["ELITE FOUR SAGE. I have seen this battle ten thousand times in my mind.","In only three do you win. Let us find out which timeline this is."],
 outro:["...This was one of the three. Extraordinary. The Champion awaits."]},
"champ-seraphina":{name:"SERAPHINA",sprite:"champ",reward:6000,ai:"boss",party:[{sp:"dragonite",lvl:52},{sp:"tyranitar",lvl:52},{sp:"metagross",lvl:52},{sp:"gengar",lvl:51},{sp:"salamence",lvl:52},{sp:"gardevoir",lvl:52}],
 intro:["CHAMPION SERAPHINA. Twelve years undefeated. Twelve years waiting for someone interesting.","Give me the battle I've been dreaming of."],
 outro:["...Beautiful. Absolutely beautiful. The crown is yours, Champion."]},
vex:{name:"VEX",sprite:"vex",reward:5000,ai:"boss",party:[{sp:"umbreon",lvl:54},{sp:"houndoom",lvl:54},{sp:"tyranitar",lvl:55},{sp:"absol",lvl:54},{sp:"darkrai",lvl:56}],
 intro:["VEX. Founder of UMBRA. While you collected badges, I collected GODS.","Giratina answers to ME now. Say goodbye to your reality, child."],
 outro:["Impossible... The seals... NO — Giratina, OBEY ME! OBEY—"]},
"admin-nyx":{name:"ADMIN NYX",sprite:"admin",reward:2000,ai:"basic",party:[{sp:"umbreon",lvl:42},{sp:"houndoom",lvl:42},{sp:"gengar",lvl:43}],
 intro:["UMBRA Admin NYX. The Rift doesn't care about your badges, kid.","My shadows will file you under 'forgotten'."],
 outro:["Tch. VEX won't like this. VEX won't like this at all."]},
"admin-kain":{name:"ADMIN KAIN",sprite:"admin",reward:2000,ai:"basic",party:[{sp:"tyranitar",lvl:43},{sp:"aggron",lvl:42},{sp:"gyarados",lvl:43}],
 intro:["ADMIN KAIN. UMBRA's wall. I've never lost. I've never needed to win pretty.","Come on then. Break yourself on me."],
 outro:["...Huh. First time for everything. The Rift is ahead. Good luck — you'll need it."]},
grunt1:{name:"UMBRA Grunt",sprite:"grunt",reward:200,ai:"basic",party:[{sp:"houndour",lvl:10},{sp:"machop",lvl:10}],
 intro:["Halt! This lab's data belongs to TEAM UMBRA now!","Hand over the NEXUS research or get stepped on!"],
 outro:["Grr... VEX said the chip was here! Fine — but UMBRA remembers!"]},
grunt2:{name:"UMBRA Grunt",sprite:"grunt",reward:350,ai:"basic",party:[{sp:"electrike",lvl:14},{sp:"houndour",lvl:14}],
 intro:["You again?! UMBRA's rift survey is CLASSIFIED, snoop!","My promotion depends on shutting you up!"],
 outro:["My promotion... my beautiful promotion..."]},
grunt3:{name:"UMBRA Grunt",sprite:"grunt",reward:900,ai:"basic",party:[{sp:"umbreon",lvl:30},{sp:"houndoom",lvl:30}],
 intro:["The second SEAL is ours! UMBRA thanks you for the warm-up!","Darkness isn't evil, kid. It's just... efficient."],
 outro:["Efficiently beaten. Noted. TELL NO ONE."]},
grunt4:{name:"UMBRA Grunt",sprite:"grunt",reward:1200,ai:"basic",party:[{sp:"gengar",lvl:38},{sp:"absol",lvl:38}],
 intro:["Last seal! UMBRA is SO close! You're not ruining this!","The boss promised us a new world. I want the beach house version!"],
 outro:["The beach house... gone..."]},
rt1:{name:"Youngster BEN",sprite:"kid",reward:100,ai:"basic",party:[{sp:"shroomish",lvl:4},{sp:"mareep",lvl:4}],
 intro:["I'm gonna be the best! Starting with YOU!"], outro:["Best... later. Best later."]},
rt2:{name:"Lass MIA",sprite:"kid",reward:120,ai:"basic",party:[{sp:"electrike",lvl:5},{sp:"abra",lvl:5}],
 intro:["My Pokémon are cuter than yours! FIGHT ME!"], outro:["Cute but weak... story of my life."]},
rt3:{name:"Hiker DOUG",sprite:"elder",reward:250,ai:"basic",party:[{sp:"geodude",lvl:9},{sp:"machop",lvl:9}],
 intro:["These mountains are my gym! You're trespassing, kid!"], outro:["Rock solid effort, kid."]},
rt4:{name:"Psychic INES",sprite:"kid",reward:280,ai:"basic",party:[{sp:"abra",lvl:10},{sp:"gastly",lvl:10}],
 intro:["I foresaw this battle. I also foresaw losing. Let's get it over with."], outro:["As foreseen."]},
rt5:{name:"Fisher HAL",sprite:"elder",reward:400,ai:"basic",party:[{sp:"magikarp",lvl:14},{sp:"magikarp",lvl:14},{sp:"electrike",lvl:15}],
 intro:["I fish all day! Battle me while the soup's on!"], outro:["The soup's ruined AND I lost?!"]},
rt6:{name:"Camper RUE",sprite:"kid",reward:420,ai:"basic",party:[{sp:"machop",lvl:16},{sp:"shroomish",lvl:16}],
 intro:["I camped here three days waiting for a challenger! WORTH IT!"], outro:["Three days... for THIS?!"]},
rt7:{name:"Climber FERN2",sprite:"elder",reward:800,ai:"basic",party:[{sp:"graveler",lvl:30},{sp:"kadabra",lvl:30}],
 intro:["The summit sorts the strong from the snack-sized!"], outro:["You're no snack. Noted."]},
rt8:{name:"Hex Maniac LIV",sprite:"kid",reward:850,ai:"basic",party:[{sp:"haunter",lvl:31},{sp:"manectric",lvl:31}],
 intro:["The spirits told me you'd come. They also told me your shoelace is untied."], outro:["The spirits owe me an apology."]},
"gym1-t1":{name:"Gym Trainer WATT",sprite:"kid",reward:300,ai:"basic",party:[{sp:"mareep",lvl:11},{sp:"electrike",lvl:11}],
 intro:["VOLTA's gym runs on SPEED! Keep up!"], outro:["Too slow... story of my battles."]},
"gym1-t2":{name:"Gym Trainer JOLT",sprite:"kid",reward:320,ai:"basic",party:[{sp:"electrike",lvl:12}],
 intro:["One Pokémon. All the voltage. Let's go!"], outro:["BZZT. Short-circuited."]},
"gym2-t1":{name:"Gym Trainer PETAL",sprite:"kid",reward:450,ai:"basic",party:[{sp:"shroomish",lvl:18},{sp:"shroomish",lvl:19}],
 intro:["Shhh... FERN's garden battles are quiet... and VIOLENT."], outro:["The flowers weep for me."]},
"gym2-t2":{name:"Gym Trainer MOSS",sprite:"kid",reward:480,ai:"basic",party:[{sp:"ivysaur",lvl:20}],
 intro:["My partner and I photosynthesize VICTORY."], outro:["We photosynthesized defeat."]},
"gym3-t1":{name:"Gym Trainer REEF",sprite:"kid",reward:650,ai:"basic",party:[{sp:"wartortle",lvl:25},{sp:"magikarp",lvl:25}],
 intro:["MARINA's gym! No lifeguard on duty! DROWN! (in battle)"], outro:["Glub... I mean... good match..."]},
"gym3-t2":{name:"Gym Trainer TIDE",sprite:"kid",reward:700,ai:"basic",party:[{sp:"gyarados",lvl:26}],
 intro:["Behold! The serpent of the harbor! TREMBLE!"], outro:["It trembled. I trembled. We all trembled."]},
"gym4-t1":{name:"Gym Trainer FANG",sprite:"kid",reward:900,ai:"basic",party:[{sp:"trapinch",lvl:32},{sp:"vibrava",lvl:33}],
 intro:["DRAKE's gym! Dragons! Well... dragon-ADJACENT!"], outro:["Adjacent to victory. So close."]},
"gym4-t2":{name:"Gym Trainer SCALE",sprite:"kid",reward:950,ai:"basic",party:[{sp:"bagon",lvl:33},{sp:"shelgon",lvl:34}],
 intro:["My dragons are still growing! Like my debt!"], outro:["Growth... stunted. Like my debt. Growing."]}
};

/* ============ MAPS ============ */
G.Maps.LIST = {

"circuit-town":{id:"circuit-town",name:"Circuit Town",w:20,h:15,music:"town",
tiles:[
"TTTTTTTTTT..TTTTTTTT",
"T..................T",
"T.######....#####..T",
"T.#....#....#...#..T",
"T.#....#....#...#..T",
"T.##DD##....##D##..T",
"T..................T",
"T..**.........**...T",
"T..................T",
"T.######....#####..T",
"T.#....#....#...#..T",
"T.#....#....#...#..T",
"T.##DD##....##D##..T",
"T..................T",
"TTTTTTTTTTTTTTTTTTTT"],
encounters:null,
npcs:[
 {x:8,y:6,sprite:"kid",dir:"down",dialog:"npc_circuit_kid",wander:true},
 {x:15,y:8,sprite:"elder",dir:"left",dialog:"npc_circuit_elder",wander:false}],
trainers:[],
warps:[{x:10,y:0,to:"route-1",tx:11,ty:16},{x:11,y:0,to:"route-1",tx:12,ty:16},
 {x:4,y:5,to:"player-house",tx:5,ty:7},{x:5,y:5,to:"player-house",tx:6,ty:7},
 {x:14,y:5,to:"circuit-lab",tx:6,ty:7}],
signs:[{x:8,y:1,text:"CIRCUIT TOWN — Where every journey gets its spark."},
 {x:2,y:6,text:"MAPLE's Lab: Pokémon research & fusion science!"},
 {x:12,y:13,text:"Poké Mart: now stocking Ultra Balls! (We believe in you.)"}],
heal:{x:4,y:12},shop:{x:14,y:12},pc:null},

"player-house":{id:"player-house",name:"Your House",w:12,h:10,music:"town",
tiles:[
"############",
"#..........#",
"#..####....#",
"#..####....#",
"#..........#",
"#..........#",
"#....##....#",
"#....##....#",
"#....DD....#",
"############"],
encounters:null,
npcs:[{x:6,y:3,sprite:"elder",dir:"down",dialog:"npc_mom",wander:false}],
trainers:[],
warps:[{x:5,y:8,to:"circuit-town",tx:4,ty:6},{x:6,y:8,to:"circuit-town",tx:5,ty:6}],
signs:[],heal:null,shop:null,pc:null},

"circuit-lab":{id:"circuit-lab",name:"NEXUS Lab",w:14,h:10,music:"town",
tiles:[
"##############",
"#............#",
"#..####..##..#",
"#..####..##..#",
"#............#",
"#............#",
"#.....##.....#",
"#.....##.....#",
"#.....DD.....#",
"##############"],
encounters:null,
npcs:[
 {x:7,y:3,sprite:"prof",dir:"down",dialog:"npc_prof",wander:false},
 {x:3,y:6,sprite:"scientist",dir:"right",dialog:"npc_aide",wander:false},
 {x:3,y:4,sprite:"scientist",dir:"down",dialog:"starter_a",wander:false},
 {x:11,y:4,sprite:"scientist",dir:"down",dialog:"starter_b",wander:false},
 {x:7,y:6,sprite:"scientist",dir:"up",dialog:"starter_c",wander:false}],
trainers:[],
warps:[{x:6,y:8,to:"circuit-town",tx:14,ty:6},{x:7,y:8,to:"circuit-town",tx:14,ty:6}],
signs:[{x:11,y:1,text:"FUSION LAB — DNA Splicers required. Ask the PROF."}],
heal:null,shop:null,pc:{x:11,y:2}},

"volt-city":{id:"volt-city",name:"Volt City",w:24,h:18,music:"town",
tiles:[
"TTTTTTTTTTT..TTTTTTTTTTT",
"T......................T",
"T.######......######...T",
"T.#....#......#....#...T",
"T.#....#......#....#...T",
"T.##DD##......##DD##...T",
"T......................T",
"T..**............**....T",
"T......................T",
"T......................T",
"T.######......#####....T",
"T.#....#......#...#....T",
"T.#....#......#...#....T",
"T.##DD##......##D##....T",
"T......................T",
"T..**............**....T",
"T......................T",
"TTTTTTTTTTT..TTTTTTTTTTT"],
encounters:null,
npcs:[
 {x:12,y:8,sprite:"kid",dir:"down",dialog:"npc_volt_kid",wander:true},
 {x:6,y:15,sprite:"clerk",dir:"up",dialog:"npc_volt_clerk",wander:false},
 {x:12,y:15,sprite:"grunt",dir:"up",dialog:"evt_umbra1",wander:false}],
trainers:[],
warps:[{x:11,y:0,to:"route-2",tx:11,ty:16},{x:12,y:0,to:"route-2",tx:12,ty:16},
 {x:11,y:17,to:"route-1",tx:11,ty:1},{x:12,y:17,to:"route-1",tx:12,ty:1},
 {x:4,y:5,to:"volt-gym",tx:7,ty:10},{x:5,y:5,to:"volt-gym",tx:8,ty:10}],
signs:[{x:12,y:1,text:"VOLT CITY — The city that never sleeps. It hums."},
 {x:2,y:6,text:"VOLT GYM — Leader VOLTA! Speed kills!"}],
heal:{x:15,y:5},shop:{x:4,y:13},pc:null},

"fern-town":{id:"fern-town",name:"Fern Town",w:20,h:15,music:"town",
tiles:[
"TTTTTTTTTTTTTTTTTTTT",
"T..................T",
"T.######....#####..T",
"T.#....#....#...#..T",
"T.#....#....#...#..T",
"T.##DD##....##D##..T",
"T..**......**......T",
"T...................",
"T...................",
"T.######...........T",
"T.#....#...........T",
"T.#....#...........T",
"T.##DD##...........T",
"T..................T",
"TTTTTTTTTT..TTTTTTTT"],
encounters:null,
npcs:[{x:10,y:7,sprite:"elder",dir:"down",dialog:"npc_fern_elder",wander:false},
 {x:13,y:7,sprite:"kid",dir:"down",dialog:"evt_tanjiro",wander:false}],
trainers:[],
warps:[{x:10,y:14,to:"route-2",tx:11,ty:1},{x:11,y:14,to:"route-2",tx:12,ty:1},
 {x:19,y:7,to:"route-3",tx:1,ty:8},{x:19,y:8,to:"route-3",tx:1,ty:9},
 {x:4,y:5,to:"fern-gym",tx:7,ty:10},{x:5,y:5,to:"fern-gym",tx:8,ty:10}],
signs:[{x:10,y:1,text:"FERN TOWN — Please water the flowers. They judge you."},
 {x:2,y:6,text:"FERN GYM — Leader FERN! Quiet strength!"}],
heal:{x:14,y:5},shop:null,pc:null},

"harbor-town":{id:"harbor-town",name:"Harbor Town",w:20,h:15,music:"town",
tiles:[
"TTTTTTTTTT..TTTTTTTT",
"T..................T",
"T.######....#####..T",
"T.#....#....#...#..T",
"T.#....#....#...#..T",
"T.##DD##....##D##..T",
"T..................T",
"T..**......**..~~~~T",
"T..............~~~~T",
"T.######.......~~~~T",
"T.#....#.......~~~~T",
"T.#....#.......~~~~T",
"T.##DD##.......~~~~T",
"T..................T",
"TTTTTTTTTTTTTTTTTTTT"],
encounters:null,
npcs:[
 {x:13,y:8,sprite:"kid",dir:"right",dialog:"npc_harbor_kid",wander:true},
 {x:6,y:7,sprite:"elder",dir:"down",dialog:"npc_harbor_elder",wander:false},
 {x:16,y:8,sprite:"kid",dir:"left",dialog:"evt_luffy",wander:false},
 {x:10,y:6,sprite:"rival",dir:"down",dialog:"evt_echo3",wander:false}],
trainers:[],
warps:[{x:0,y:7,to:"route-3",tx:22,ty:8},{x:0,y:8,to:"route-3",tx:22,ty:9},
 {x:10,y:0,to:"route-4",tx:11,ty:16},{x:11,y:0,to:"route-4",tx:12,ty:16},
 {x:4,y:5,to:"harbor-gym",tx:7,ty:10},{x:5,y:5,to:"harbor-gym",tx:8,ty:10}],
signs:[{x:10,y:1,text:"HARBOR TOWN — Mind the Gyarados. They're sensitive."},
 {x:2,y:6,text:"HARBOR GYM — Leader MARINA! Ride the tide!"}],
heal:{x:14,y:5},shop:{x:4,y:12},pc:null},

"summit-town":{id:"summit-town",name:"Summit Town",w:20,h:15,music:"town",
tiles:[
"TTTTTTTTTT..TTTTTTTT",
"T..................T",
"T.######....#####..T",
"T.#....#....#...#..T",
"T.#....#....#...#..T",
"T.##DD##....##D##..T",
"T..o........o......T",
"T..................T",
"T..................T",
"T.######....#####..T",
"T.#....#....#...#..T",
"T.#....#....#...#..T",
"T.##DD##....##D##..T",
"T..................T",
"TTTTTTTTTT..TTTTTTTT"],
encounters:null,
npcs:[{x:10,y:7,sprite:"elder",dir:"down",dialog:"npc_summit_elder",wander:false},
 {x:10,y:10,sprite:"rival",dir:"up",dialog:"evt_echo4",wander:false}],
trainers:[],
warps:[{x:10,y:14,to:"route-4",tx:11,ty:1},{x:11,y:14,to:"route-4",tx:12,ty:1},
 {x:10,y:0,to:"victory-road",tx:11,ty:18},{x:11,y:0,to:"victory-road",tx:12,ty:18},
 {x:4,y:5,to:"summit-gym",tx:7,ty:10},{x:5,y:5,to:"summit-gym",tx:8,ty:10}],
signs:[{x:10,y:1,text:"SUMMIT TOWN — Last stop before Victory Road. Breathe."},
 {x:2,y:6,text:"SUMMIT GYM — Leader DRAKE! Dragons fear HIM!"}],
heal:{x:14,y:5},shop:{x:14,y:12},pc:{x:4,y:12}},

"route-1":{id:"route-1",name:"Route 1",w:24,h:18,music:"route",
tiles:[
"TTTTTTTTTTT..TTTTTTTTTTT",
"T.,,,,,TT..TT,,,,,,....T",
"T.,,,,,TT..TT,,,,,,....T",
"T...,,,TT..TT,,,,,,....T",
"T..TT..TT..TT..TT..TT..T",
"T.,,,,,TT..TT,,,,,,....T",
"T.,,,,,TT..TT,,,,,,....T",
"T...,,,TT..TT,,,,,,....T",
"T..TT..TT..TT..TT..TT..T",
"T.,,,,,TT..TT,,,,,,....T",
"T.,,,*,TT..TT,,,,,,....T",
"T...,,,TT..TT,,,,,,....T",
"T..TT..TT..TT..TT..TT..T",
"T.,,,,,TT..TT,,,,,,....T",
"T.,,,,,TT..TT,,,,,,....T",
"T...,,,TT..TT,,,,,,....T",
"T..TT..TT..TT..TT..TT..T",
"TTTTTTTTTTT..TTTTTTTTTTT"],
encounters:{rate:12,table:[{sp:"caterpie",min:2,max:4,w:12},{sp:"weedle",min:2,max:4,w:12},{sp:"pidgey",min:2,max:5,w:12},{sp:"rattata",min:2,max:5,w:10},{sp:"spearow",min:3,max:5,w:8},{sp:"nidoran-f",min:3,max:5,w:8},{sp:"nidoran-m",min:3,max:5,w:8},{sp:"shroomish",min:2,max:4,w:30},{sp:"mareep",min:2,max:4,w:30},{sp:"electrike",min:3,max:5,w:25},{sp:"abra",min:3,max:4,w:15}]},
npcs:[],trainers:[{id:"rt1",x:6,y:8,dir:"right"},{id:"rt2",x:17,y:12,dir:"left"}],
warps:[{x:11,y:0,to:"volt-city",tx:11,ty:16},{x:12,y:0,to:"volt-city",tx:12,ty:16},
 {x:11,y:17,to:"circuit-town",tx:10,ty:1},{x:12,y:17,to:"circuit-town",tx:11,ty:1}],
signs:[{x:9,y:9,text:"ROUTE 1 — Watch for rustling grass!"}],heal:null,shop:null,pc:null},

"route-2":{id:"route-2",name:"Route 2",w:24,h:18,music:"route",
tiles:[
"TTTTTTTTTTT..TTTTTTTTTTT",
"T.,,,,,TT..TT,,,,,,TT..T",
"T.,,,,,TT..TT,,,,,,TT..T",
"T...,,,TT..TT,,,,,,....T",
"T..TT..TT..TT..TT..TT..T",
"T.,,,,,TT..TT,,,,,,TT..T",
"T.,,,,,TT..TT,,o,,,TT..T",
"T...,,,TT..TT,,,,,,....T",
"T..TT..TT..TT..TT..TT..T",
"T.,,,,,TT..TT,,,,,,TT..T",
"T.,,,,,TT..TT,,,,,,TT..T",
"T...,,,TT..TT..o,,,....T",
"T..TT..TT..TT..TT..TT..T",
"T.,,,,,TT..TT,,,,,,TT..T",
"T.,,,,,TT..TT,,,,,,TT..T",
"T...,,,TT..TT,,,,,,....T",
"T..TT..TT..TT..TT..TT..T",
"TTTTTTTTTTT..TTTTTTTTTTT"],
encounters:{rate:12,table:[{sp:"ekans",min:4,max:7,w:10},{sp:"sandshrew",min:4,max:7,w:10},{sp:"mankey",min:4,max:8,w:10},{sp:"oddish",min:4,max:7,w:10},{sp:"paras",min:4,max:7,w:10},{sp:"venonat",min:4,max:8,w:8},{sp:"diglett",min:4,max:8,w:10},{sp:"meowth",min:4,max:8,w:8},{sp:"psyduck",min:4,max:7,w:8},{sp:"poliwag",min:4,max:7,w:8},{sp:"growlithe",min:5,max:8,w:6},{sp:"bellsprout",min:4,max:7,w:10},{sp:"ponyta",min:5,max:8,w:6},{sp:"geodude",min:7,max:10,w:30},{sp:"machop",min:7,max:10,w:30},{sp:"gastly",min:8,max:10,w:20},{sp:"abra",min:8,max:11,w:20},{sp:"sparkit",min:8,max:10,w:5},{sp:"aquil",min:8,max:10,w:5},{sp:"terrafen",min:8,max:10,w:5}]},
npcs:[
 {x:17,y:4,sprite:"grunt",dir:"left",dialog:"evt_umbra2",wander:false},
 {x:11,y:9,sprite:"rival",dir:"down",dialog:"evt_echo2",wander:false}],
trainers:[{id:"rt3",x:6,y:6,dir:"right"},{id:"rt4",x:17,y:12,dir:"left"}],
warps:[{x:11,y:0,to:"fern-town",tx:10,ty:13},{x:12,y:0,to:"fern-town",tx:11,ty:13},
 {x:11,y:17,to:"volt-city",tx:11,ty:1},{x:12,y:17,to:"volt-city",tx:12,ty:1}],
signs:[{x:9,y:9,text:"ROUTE 2 — The forest hums here. So do the Voltorb. (There are no Voltorb.)"}],
heal:null,shop:null,pc:null},

"route-3":{id:"route-3",name:"Route 3",w:24,h:18,music:"route",
tiles:[
"TTTTTTTTTTTTTTTTTTTTTTTT",
"T,,,,TT..TT,,,,TT~~~~..T",
"T,,,,TT..TT,,,,TT~~~~..T",
"T,,,,TT..TT,,,,TT..~~..T",
"T..,,TT..TT..,,TT..o...T",
"T..,,TT..TT..,,TT.ooo..T",
"T,,,,TT..TT,,,,TT......T",
"T,,,,TT..TT,,,,TT......T",
"........................",
"........................",
"T,,,,TT..TT,,,,TT......T",
"T..,,TT..TT..,,TT......T",
"T..,,TT..TT..,,TT......T",
"T,,,,TT..TT,,,,TT......T",
"T,,,,TT..TT,,,,TT..**..T",
"T..,,TT..TT..,,TT......T",
"T..,,TT..TT..,,TT......T",
"TTTTTTTTTTTTTTTTTTTTTTTT"],
encounters:{rate:12,table:[{sp:"metapod",min:8,max:11,w:8},{sp:"kakuna",min:8,max:11,w:8},{sp:"butterfree",min:10,max:13,w:6},{sp:"beedrill",min:10,max:13,w:6},{sp:"pidgeotto",min:10,max:14,w:10},{sp:"raticate",min:9,max:13,w:8},{sp:"fearow",min:11,max:14,w:6},{sp:"arbok",min:10,max:14,w:8},{sp:"sandslash",min:10,max:13,w:8},{sp:"nidorina",min:9,max:13,w:8},{sp:"nidorino",min:9,max:13,w:8},{sp:"clefairy",min:8,max:12,w:6},{sp:"vulpix",min:8,max:12,w:8},{sp:"jigglypuff",min:8,max:12,w:8},{sp:"zubat",min:8,max:12,w:10},{sp:"golbat",min:11,max:14,w:6},{sp:"gloom",min:9,max:13,w:8},{sp:"parasect",min:10,max:13,w:6},{sp:"venomoth",min:11,max:14,w:6},{sp:"dugtrio",min:11,max:14,w:6},{sp:"persian",min:11,max:14,w:6},{sp:"golduck",min:11,max:14,w:6},{sp:"primeape",min:11,max:14,w:6},{sp:"arcanine",min:12,max:14,w:4},{sp:"poliwhirl",min:10,max:13,w:6},{sp:"weepinbell",min:9,max:13,w:6},{sp:"drowzee",min:8,max:12,w:8},{sp:"voltorb",min:8,max:12,w:8},{sp:"exeggcute",min:8,max:12,w:6},{sp:"cubone",min:8,max:12,w:8},{sp:"koffing",min:8,max:12,w:8},{sp:"sentret",min:8,max:11,w:8},{sp:"hoothoot",min:8,max:12,w:8},{sp:"ledyba",min:8,max:11,w:6},{sp:"spinarak",min:8,max:12,w:8},{sp:"natu",min:8,max:12,w:8},{sp:"hoppip",min:8,max:11,w:6},{sp:"pineco",min:8,max:12,w:6},{sp:"doduo",min:8,max:12,w:8},{sp:"grimer",min:8,max:12,w:8},{sp:"electrike",min:14,max:17,w:30},{sp:"shroomish",min:14,max:16,w:25},{sp:"machop",min:14,max:17,w:25},{sp:"abra",min:15,max:17,w:20}],
 water:[{sp:"magikarp",min:10,max:15,w:100}]},
npcs:[{x:18,y:6,sprite:"kid",dir:"down",dialog:"evt_goku_crash",wander:false}],
trainers:[{id:"rt5",x:8,y:6,dir:"right"},{id:"rt6",x:14,y:12,dir:"left"}],
warps:[{x:0,y:8,to:"fern-town",tx:18,ty:7},{x:0,y:9,to:"fern-town",tx:18,ty:8},
 {x:23,y:8,to:"harbor-town",tx:1,ty:7},{x:23,y:9,to:"harbor-town",tx:1,ty:8}],
signs:[{x:20,y:5,text:"WARNING: Crater. Something fell from the sky. It is yelling."}],
heal:null,shop:null,pc:null},

"route-4":{id:"route-4",name:"Route 4",w:24,h:18,music:"route",
tiles:[
"TTTTTTTTTTT..TTTTTTTTTTT",
"T..o,,,,TT..TT,,,,o....T",
"T..o,,,,TT..TT,,,,o....T",
"T....,,TT..TT..,,......T",
"T..o...TT..TT...o..o...T",
"T......TT..TT..........T",
"T..,,..TT..TT..,,..o...T",
"T..,,..TT..TT..,,......T",
"T......TT..TT......o...T",
"T..o...TT..TT...o......T",
"T......TT..TT..........T",
"T..,,..TT..TT..,,..o...T",
"T..,,..TT..TT..,,......T",
"T......TT..TT......o...T",
"T..o...TT..TT...o......T",
"T......TT..TT..........T",
"T..,,..TT..TT..,,......T",
"TTTTTTTTTTT..TTTTTTTTTTT"],
encounters:{rate:14,table:[{sp:"furret",min:18,max:24,w:8},{sp:"noctowl",min:20,max:26,w:8},{sp:"ledian",min:19,max:25,w:6},{sp:"ariados",min:20,max:26,w:8},{sp:"crobat",min:22,max:28,w:6},{sp:"xatu",min:20,max:26,w:8},{sp:"bellossom",min:22,max:27,w:6},{sp:"marill",min:18,max:23,w:8},{sp:"azumarill",min:22,max:27,w:6},{sp:"skiploom",min:18,max:24,w:6},{sp:"jumpluff",min:23,max:28,w:6},{sp:"aipom",min:18,max:24,w:8},{sp:"sunkern",min:18,max:22,w:6},{sp:"sunflora",min:22,max:27,w:6},{sp:"yanma",min:19,max:25,w:8},{sp:"wooper",min:18,max:23,w:8},{sp:"quagsire",min:22,max:27,w:6},{sp:"murkrow",min:20,max:26,w:8},{sp:"misdreavus",min:20,max:26,w:6},{sp:"girafarig",min:20,max:26,w:8},{sp:"dunsparce",min:18,max:24,w:6},{sp:"gligar",min:20,max:26,w:8},{sp:"snubbull",min:18,max:23,w:8},{sp:"granbull",min:22,max:27,w:6},{sp:"heracross",min:22,max:28,w:6},{sp:"sneasel",min:20,max:26,w:8},{sp:"teddiursa",min:18,max:24,w:8},{sp:"ursaring",min:23,max:28,w:6},{sp:"slugma",min:18,max:24,w:8},{sp:"magcargo",min:23,max:28,w:6},{sp:"swinub",min:18,max:24,w:8},{sp:"piloswine",min:23,max:28,w:6},{sp:"stantler",min:20,max:26,w:8},{sp:"smeargle",min:20,max:26,w:6},{sp:"tyrogue",min:18,max:23,w:6},{sp:"hitmontop",min:22,max:27,w:6},{sp:"chikorita",min:18,max:22,w:4},{sp:"cyndaquil",min:18,max:22,w:4},{sp:"totodile",min:18,max:22,w:4},{sp:"sudowoodo",min:20,max:26,w:6},{sp:"graveler",min:28,max:32,w:30},{sp:"kadabra",min:28,max:31,w:25},{sp:"haunter",min:29,max:32,w:25},{sp:"machoke",min:30,max:33,w:20}]},
npcs:[
 {x:14,y:8,sprite:"kid",dir:"down",dialog:"evt_gojo",wander:false}],
trainers:[{id:"rt7",x:6,y:7,dir:"right"},{id:"rt8",x:17,y:11,dir:"left"}],
warps:[{x:11,y:0,to:"summit-town",tx:10,ty:13},{x:12,y:0,to:"summit-town",tx:11,ty:13},
 {x:11,y:17,to:"harbor-town",tx:10,ty:1},{x:12,y:17,to:"harbor-town",tx:11,ty:1}],
signs:[{x:9,y:9,text:"ROUTE 4 — Thin air, thick skulls. Both help in battle."}],
heal:null,shop:null,pc:null},

"volt-gym":{id:"volt-gym",name:"Volt Gym",w:16,h:12,music:"gym",
tiles:[
"################",
"#..............#",
"#..............#",
"#....######....#",
"#....#....#....#",
"#..............#",
"#..T........T..#",
"#..............#",
"#..............#",
"#..............#",
"#......DD......#",
"################"],
encounters:null,
npcs:[{x:7,y:2,sprite:"leader",dir:"down",dialog:"gym1_leader",wander:false}],
trainers:[{id:"gym1-t1",x:3,y:6,dir:"right"},{id:"gym1-t2",x:12,y:6,dir:"left"}],
warps:[{x:7,y:10,to:"volt-city",tx:4,ty:6},{x:8,y:10,to:"volt-city",tx:5,ty:6}],
signs:[],heal:null,shop:null,pc:null},

"fern-gym":{id:"fern-gym",name:"Fern Gym",w:16,h:12,music:"gym",
tiles:[
"################",
"#..**........**#",
"#..............#",
"#....######....#",
"#....#,,,,#....#",
"#....,,,,,,....#",
"#..T..,,,,..T..#",
"#....,,,,,,....#",
"#....#,,,,#....#",
"#..**........**#",
"#......DD......#",
"################"],
encounters:null,
npcs:[{x:7,y:2,sprite:"leader",dir:"down",dialog:"gym2_leader",wander:false}],
trainers:[{id:"gym2-t1",x:3,y:6,dir:"right"},{id:"gym2-t2",x:12,y:6,dir:"left"}],
warps:[{x:7,y:10,to:"fern-town",tx:4,ty:6},{x:8,y:10,to:"fern-town",tx:5,ty:6}],
signs:[],heal:null,shop:null,pc:null},

"harbor-gym":{id:"harbor-gym",name:"Harbor Gym",w:16,h:12,music:"gym",
tiles:[
"################",
"#..~~~~~~~~~~..#",
"#..............#",
"#....######....#",
"#....#~~~~#....#",
"#......~~......#",
"#..T........T..#",
"#......~~......#",
"#....#~~~~#....#",
"#..~~~~~~~~~~..#",
"#......DD......#",
"################"],
encounters:null,
npcs:[{x:7,y:2,sprite:"leader",dir:"down",dialog:"gym3_leader",wander:false}],
trainers:[{id:"gym3-t1",x:3,y:6,dir:"right"},{id:"gym3-t2",x:12,y:6,dir:"left"}],
warps:[{x:7,y:10,to:"harbor-town",tx:4,ty:6},{x:8,y:10,to:"harbor-town",tx:5,ty:6}],
signs:[],heal:null,shop:null,pc:null},

"summit-gym":{id:"summit-gym",name:"Summit Gym",w:16,h:12,music:"gym",
tiles:[
"################",
"#..o........o..#",
"#..............#",
"#....######....#",
"#....#....#....#",
"#..o........o..#",
"#..T........T..#",
"#..............#",
"#..o........o..#",
"#..............#",
"#......DD......#",
"################"],
encounters:null,
npcs:[{x:7,y:2,sprite:"leader",dir:"down",dialog:"gym4_leader",wander:false}],
trainers:[{id:"gym4-t1",x:3,y:6,dir:"right"},{id:"gym4-t2",x:12,y:6,dir:"left"}],
warps:[{x:7,y:10,to:"summit-town",tx:4,ty:6},{x:8,y:10,to:"summit-town",tx:5,ty:6}],
signs:[],heal:null,shop:null,pc:null},

"victory-road":{id:"victory-road",name:"Victory Road",w:24,h:20,music:"gym",
tiles:[
"TTTTTTTTTTT..TTTTTTTTTTT",
"T..o....o.....o....o...T",
"T......................T",
"T..o..oooo..oooo..o....T",
"T......o......o........T",
"T..o...o..oo..o...o....T",
"T......o..oo..o........T",
"T..o...o......o...o....T",
"T......oooo..oooo......T",
"T..o................o..T",
"T.....o..oooooo..o.....T",
"T..o..o..o....o..o..o..T",
"T.....o..o.oo.o..o.....T",
"T..o..o..o.oo.o..o..o..T",
"T.....o..o....o..o.....T",
"T..o..o..oooooo..o..o..T",
"T.....o..........o.....T",
"T..o.....o..o.....o....T",
"T......................T",
"TTTTTTTTTTT..TTTTTTTTTTT"],
encounters:{rate:14,table:[{sp:"pidgeot",min:36,max:44,w:6},{sp:"nidoqueen",min:38,max:46,w:6},{sp:"nidoking",min:38,max:46,w:6},{sp:"clefable",min:36,max:44,w:6},{sp:"ninetales",min:37,max:45,w:6},{sp:"wigglytuff",min:36,max:44,w:6},{sp:"vileplume",min:37,max:45,w:6},{sp:"poliwrath",min:37,max:45,w:6},{sp:"victreebel",min:37,max:45,w:6},{sp:"rapidash",min:36,max:44,w:6},{sp:"slowbro",min:37,max:45,w:6},{sp:"magneton",min:36,max:44,w:8},{sp:"dodrio",min:36,max:44,w:6},{sp:"dewgong",min:37,max:45,w:6},{sp:"muk",min:37,max:45,w:6},{sp:"cloyster",min:38,max:46,w:6},{sp:"onix",min:35,max:43,w:8},{sp:"hypno",min:36,max:44,w:8},{sp:"electrode",min:37,max:45,w:6},{sp:"exeggutor",min:38,max:46,w:6},{sp:"marowak",min:37,max:45,w:6},{sp:"hitmonlee",min:38,max:46,w:6},{sp:"hitmonchan",min:38,max:46,w:6},{sp:"lickitung",min:36,max:44,w:6},{sp:"weezing",min:37,max:45,w:6},{sp:"rhyhorn",min:35,max:42,w:8},{sp:"rhydon",min:40,max:48,w:6},{sp:"chansey",min:38,max:46,w:4},{sp:"tangela",min:36,max:44,w:6},{sp:"kangaskhan",min:38,max:46,w:6},{sp:"electabuzz",min:37,max:45,w:6},{sp:"magmar",min:37,max:45,w:6},{sp:"pinsir",min:37,max:45,w:6},{sp:"tauros",min:38,max:46,w:6},{sp:"porygon",min:36,max:44,w:6},{sp:"skarmory",min:38,max:46,w:6},{sp:"donphan",min:37,max:45,w:6},{sp:"steelix",min:40,max:48,w:6},{sp:"shuckle",min:36,max:44,w:6},{sp:"porygon2",min:38,max:46,w:6},{sp:"miltank",min:37,max:45,w:6},{sp:"blissey",min:40,max:48,w:4},{sp:"slaking",min:40,max:48,w:6},{sp:"ninjask",min:37,max:45,w:6},{sp:"shedinja",min:37,max:45,w:4},{sp:"exploud",min:38,max:46,w:6},{sp:"hariyama",min:37,max:45,w:6},{sp:"medicham",min:37,max:45,w:6},{sp:"camerupt",min:37,max:45,w:6},{sp:"torkoal",min:36,max:44,w:6},{sp:"grumpig",min:37,max:45,w:6},{sp:"cacturne",min:37,max:45,w:6},{sp:"altaria",min:38,max:46,w:6},{sp:"zangoose",min:37,max:45,w:6},{sp:"seviper",min:37,max:45,w:6},{sp:"claydol",min:38,max:46,w:6},{sp:"cradily",min:38,max:46,w:6},{sp:"armaldo",min:38,max:46,w:6},{sp:"kecleon",min:37,max:45,w:6},{sp:"banette",min:38,max:46,w:6},{sp:"tropius",min:37,max:45,w:6},{sp:"glalie",min:38,max:46,w:6},{sp:"walrein",min:38,max:46,w:6},{sp:"relicanth",min:37,max:45,w:6},{sp:"bayleef",min:35,max:40,w:6},{sp:"quilava",min:35,max:40,w:6},{sp:"croconaw",min:35,max:40,w:6},{sp:"grovyle",min:35,max:40,w:6},{sp:"combusken",min:35,max:40,w:6},{sp:"marshtomp",min:35,max:40,w:6},{sp:"raichu",min:36,max:44,w:6},{sp:"forretress",min:37,max:45,w:6},{sp:"phanpy",min:35,max:40,w:6},{sp:"graveler",min:38,max:42,w:30},{sp:"haunter",min:38,max:42,w:25},{sp:"kadabra",min:39,max:43,w:25},{sp:"machoke",min:40,max:44,w:15},{sp:"larvitar",min:38,max:40,w:5}]},
npcs:[
 {x:6,y:9,sprite:"kid",dir:"down",dialog:"evt_naruto",wander:false},
 {x:11,y:14,sprite:"grunt",dir:"up",dialog:"evt_umbra4",wander:false}],
trainers:[],
warps:[{x:11,y:0,to:"pokemon-league",tx:9,ty:13},{x:12,y:0,to:"pokemon-league",tx:10,ty:13},
 {x:11,y:19,to:"summit-town",tx:10,ty:1},{x:12,y:19,to:"summit-town",tx:11,ty:1}],
signs:[{x:12,y:9,text:"VICTORY ROAD — Only the worthy pass. The rocks are the exam."}],
heal:null,shop:null,pc:null},

"pokemon-league":{id:"pokemon-league",name:"Pokémon League",w:20,h:16,music:"gym",
tiles:[
"####################",
"#..................#",
"#..................#",
"#.....######.......#",
"#..................#",
"#..................#",
"#..................#",
"#..................#",
"#..................#",
"#..................#",
"#..................#",
"#..................#",
"#..................#",
"#..................#",
"#.......DD.........#",
"####################"],
encounters:null,
npcs:[
 {x:3,y:5,sprite:"elite",dir:"down",dialog:"e4_kaia",wander:false},
 {x:16,y:5,sprite:"elite",dir:"down",dialog:"e4_mortis",wander:false},
 {x:3,y:8,sprite:"elite",dir:"down",dialog:"e4_ferro",wander:false},
 {x:16,y:8,sprite:"elite",dir:"down",dialog:"e4_sage",wander:false},
 {x:9,y:2,sprite:"champ",dir:"down",dialog:"champ_seraphina",wander:false},
 {x:10,y:11,sprite:"rival",dir:"up",dialog:"evt_echo5",wander:false}],
trainers:[],
warps:[{x:9,y:14,to:"victory-road",tx:11,ty:1},{x:10,y:14,to:"victory-road",tx:12,ty:1}],
signs:[{x:9,y:13,text:"POKéMON LEAGUE — Four elites. One champion. Zero excuses."}],
heal:{x:2,y:13},shop:null,pc:{x:17,y:13}},

"distortion-1":{id:"distortion-1",name:"Distortion World B1",w:24,h:20,music:"distortion",
tiles:[
"TTTTTTTTTTT..TTTTTTTTTTT",
"T.....o..........o.....T",
"T......................T",
"T..o................o..T",
"T......................T",
"T.......oo.....oo......T",
"T......................T",
"T..o................o..T",
"T......................T",
"T......o........o......T",
"T......................T",
"T..o................o..T",
"T......................T",
"T.......oo.....oo......T",
"T......................T",
"T..o................o..T",
"T......................T",
"T.....o..........o.....T",
"T......................T",
"TTTTTTTTTTT..TTTTTTTTTTT"],
encounters:{rate:14,table:[{sp:"unown",min:40,max:48,w:8},{sp:"wobbuffet",min:42,max:50,w:6},{sp:"shuppet",min:40,max:48,w:8},{sp:"duskull",min:40,max:48,w:8},{sp:"chimecho",min:42,max:50,w:6},{sp:"lunatone",min:42,max:52,w:6},{sp:"solrock",min:42,max:52,w:6},{sp:"baltoy",min:40,max:48,w:8},{sp:"gengar",min:45,max:50,w:30},{sp:"alakazam",min:45,max:50,w:25},{sp:"houndoom",min:46,max:50,w:25},{sp:"umbreon",min:46,max:50,w:20}]},
npcs:[
 {x:11,y:10,sprite:"kid",dir:"up",dialog:"evt_ichigo",wander:false}],
trainers:[{id:"admin-nyx",x:12,y:8,dir:"down"}],
warps:[{x:11,y:0,to:"distortion-2",tx:11,ty:18},{x:12,y:0,to:"distortion-2",tx:12,ty:18}],
signs:[{x:12,y:10,text:"The world folds here. Gravity is a suggestion."}],
heal:null,shop:null,pc:null},

"distortion-2":{id:"distortion-2",name:"Distortion World B2",w:24,h:20,music:"distortion",
tiles:[
"TTTTTTTTTTT..TTTTTTTTTTT",
"T......................T",
"T..o.....o......o....o.T",
"T......................T",
"T.....oo........oo.....T",
"T......................T",
"T..o................o..T",
"T......................T",
"T........o....o........T",
"T......................T",
"T..o................o..T",
"T......................T",
"T.....oo........oo.....T",
"T......................T",
"T..o.....o......o....o.T",
"T......................T",
"T......................T",
"T.....o..........o.....T",
"T......................T",
"TTTTTTTTTTT..TTTTTTTTTTT"],
encounters:{rate:14,table:[{sp:"sableye",min:42,max:52,w:8},{sp:"wynaut",min:42,max:50,w:6},{sp:"dusclops",min:44,max:54,w:6},{sp:"gengar",min:47,max:52,w:30},{sp:"umbreon",min:47,max:52,w:25},{sp:"houndoom",min:48,max:52,w:25},{sp:"absol",min:48,max:52,w:20}]},
npcs:[{x:11,y:3,sprite:"vex",dir:"down",dialog:"evt_vex",wander:false}],
trainers:[{id:"admin-kain",x:12,y:10,dir:"down"}],
warps:[{x:11,y:0,to:"circuit-town",tx:10,ty:1},{x:12,y:0,to:"circuit-town",tx:11,ty:1},
 {x:11,y:19,to:"distortion-1",tx:11,ty:1},{x:12,y:19,to:"distortion-1",tx:12,ty:1}],
signs:[],
heal:null,shop:null,pc:null},

"rift-den":{id:"rift-den",name:"Rift Den",w:20,h:16,music:"distortion",
tiles:[
"####################",
"#..................#",
"#....o........o....#",
"#....,,,,,,,,,,....#",
"#....,,,,,,,,,,....#",
"#..o............o..#",
"#..................#",
"#.......~~.........#",
"#.......~~.........#",
"#..................#",
"#..o............o..#",
"#....,,,,,,,,,,....#",
"#....,,,,,,,,,,....#",
"#....o........o....#",
"#.......DD.........#",
"####################"],
encounters:{rate:12,table:[{sp:"tentacool",min:45,max:55,w:8},{sp:"tentacruel",min:50,max:60,w:6},{sp:"krabby",min:45,max:55,w:8},{sp:"kingler",min:50,max:60,w:6},{sp:"horsea",min:45,max:55,w:8},{sp:"seadra",min:50,max:60,w:6},{sp:"kingdra",min:52,max:62,w:6},{sp:"goldeen",min:45,max:55,w:8},{sp:"seaking",min:50,max:60,w:6},{sp:"staryu",min:45,max:55,w:8},{sp:"starmie",min:50,max:60,w:6},{sp:"slowpoke",min:45,max:55,w:8},{sp:"slowking",min:52,max:62,w:6},{sp:"seel",min:45,max:55,w:8},{sp:"shellder",min:45,max:55,w:8},{sp:"politoed",min:50,max:60,w:6},{sp:"omanyte",min:45,max:55,w:6},{sp:"omastar",min:52,max:62,w:6},{sp:"kabuto",min:45,max:55,w:6},{sp:"kabutops",min:52,max:62,w:6},{sp:"remoraid",min:45,max:55,w:8},{sp:"octillery",min:50,max:60,w:6},{sp:"qwilfish",min:48,max:58,w:6},{sp:"corsola",min:46,max:56,w:6},{sp:"mantine",min:50,max:60,w:6},{sp:"delibird",min:46,max:56,w:6},{sp:"wailmer",min:45,max:55,w:8},{sp:"wailord",min:52,max:62,w:6},{sp:"barboach",min:45,max:55,w:8},{sp:"whiscash",min:50,max:60,w:6},{sp:"corphish",min:45,max:55,w:8},{sp:"crawdaunt",min:50,max:60,w:6},{sp:"luvdisc",min:45,max:55,w:8},{sp:"feebas",min:45,max:52,w:6},{sp:"milotic",min:52,max:62,w:6},{sp:"spheal",min:45,max:55,w:8},{sp:"sealeo",min:50,max:60,w:6},{sp:"clamperl",min:45,max:55,w:6},{sp:"huntail",min:50,max:60,w:6},{sp:"gorebyss",min:50,max:60,w:6},{sp:"carvanha",min:45,max:55,w:8},{sp:"sharpedo",min:50,max:60,w:6},{sp:"chinchou",min:45,max:55,w:8},{sp:"lanturn",min:50,max:60,w:6},{sp:"pichu",min:45,max:52,w:6},{sp:"cleffa",min:45,max:52,w:6},{sp:"igglybuff",min:45,max:52,w:6},{sp:"togepi",min:45,max:52,w:6},{sp:"togetic",min:50,max:58,w:6},{sp:"elekid",min:45,max:55,w:6},{sp:"magby",min:45,max:55,w:6},{sp:"smoochum",min:45,max:55,w:6},{sp:"azurill",min:45,max:52,w:6},{sp:"ditto",min:48,max:58,w:6},{sp:"farfetchd",min:46,max:56,w:6},{sp:"magnemite",min:45,max:55,w:8},{sp:"mr-mime",min:48,max:58,w:6},{sp:"jynx",min:48,max:58,w:6},{sp:"snorunt",min:45,max:55,w:8},{sp:"castform",min:48,max:58,w:6},{sp:"lileep",min:46,max:56,w:6},{sp:"treecko",min:45,max:52,w:6},{sp:"torchic",min:45,max:52,w:6},{sp:"mudkip",min:45,max:52,w:6},{sp:"poochyena",min:45,max:55,w:8},{sp:"mightyena",min:50,max:60,w:6},{sp:"zigzagoon",min:45,max:55,w:8},{sp:"linoone",min:50,max:60,w:6},{sp:"wurmple",min:45,max:52,w:8},{sp:"silcoon",min:46,max:54,w:6},{sp:"beautifly",min:50,max:58,w:6},{sp:"cascoon",min:46,max:54,w:6},{sp:"dustox",min:50,max:58,w:6},{sp:"lotad",min:45,max:55,w:8},{sp:"lombre",min:48,max:58,w:6},{sp:"ludicolo",min:52,max:62,w:6},{sp:"seedot",min:45,max:55,w:8},{sp:"nuzleaf",min:48,max:58,w:6},{sp:"shiftry",min:52,max:62,w:6},{sp:"taillow",min:45,max:55,w:8},{sp:"swellow",min:50,max:60,w:6},{sp:"wingull",min:45,max:55,w:8},{sp:"pelipper",min:50,max:60,w:6},{sp:"surskit",min:45,max:55,w:8},{sp:"masquerain",min:50,max:60,w:6},{sp:"slakoth",min:45,max:55,w:8},{sp:"vigoroth",min:48,max:58,w:6},{sp:"nincada",min:45,max:55,w:8},{sp:"whismur",min:45,max:55,w:8},{sp:"loudred",min:48,max:58,w:6},{sp:"makuhita",min:45,max:55,w:8},{sp:"nosepass",min:46,max:56,w:6},{sp:"skitty",min:45,max:55,w:8},{sp:"delcatty",min:50,max:60,w:6},{sp:"mawile",min:48,max:58,w:6},{sp:"meditite",min:45,max:55,w:8},{sp:"plusle",min:46,max:56,w:6},{sp:"minun",min:46,max:56,w:6},{sp:"volbeat",min:46,max:56,w:6},{sp:"illumise",min:46,max:56,w:6},{sp:"roselia",min:46,max:56,w:8},{sp:"gulpin",min:45,max:55,w:8},{sp:"swalot",min:50,max:60,w:6},{sp:"numel",min:45,max:55,w:8},{sp:"spoink",min:45,max:55,w:8},{sp:"spinda",min:46,max:56,w:6},{sp:"cacnea",min:45,max:55,w:8},{sp:"swablu",min:45,max:55,w:8},{sp:"meganium",min:54,max:64,w:4},{sp:"typhlosion",min:54,max:64,w:4},{sp:"feraligatr",min:54,max:64,w:4},{sp:"sceptile",min:54,max:64,w:4},{sp:"blaziken",min:54,max:64,w:4},{sp:"swampert",min:54,max:64,w:4},{sp:"anorith",min:46,max:56,w:6},{sp:"gengar",min:45,max:50,w:20},{sp:"alakazam",min:45,max:50,w:15},{sp:"umbreon",min:46,max:50,w:15},{sp:"houndoom",min:46,max:50,w:15},{sp:"sparkit",min:45,max:50,w:5},{sp:"aquil",min:45,max:50,w:5},{sp:"terrafen",min:45,max:50,w:5},{sp:"goku",min:50,max:55,w:5},{sp:"luffy",min:50,max:55,w:5},{sp:"naruto",min:50,max:55,w:5}]},
npcs:[
 {x:9,y:5,sprite:"scientist",dir:"down",dialog:"npc_rift_terminal",wander:false},
 {x:5,y:5,sprite:"kid",dir:"down",dialog:"rift_kanto",wander:false},
 {x:14,y:5,sprite:"kid",dir:"down",dialog:"rift_johto",wander:false},
 {x:5,y:10,sprite:"kid",dir:"up",dialog:"rift_hoenn",wander:false},
 {x:14,y:10,sprite:"kid",dir:"up",dialog:"rift_sinnoh",wander:false},
 {x:9,y:3,sprite:"kid",dir:"down",dialog:"rift_unova",wander:false},
 {x:9,y:12,sprite:"kid",dir:"up",dialog:"rift_god",wander:false},
 {x:4,y:7,sprite:"rival",dir:"right",dialog:"evt_saitama_rift",wander:false}],
trainers:[],
warps:[{x:9,y:14,to:"circuit-town",tx:10,ty:1},{x:10,y:14,to:"circuit-town",tx:11,ty:1}],
signs:[{x:9,y:13,text:"RIFT DEN — North & south groves: CROSSOVER GROVE. Rare starters wander the grass. Bring Ultra Balls."}],
heal:{x:2,y:13},shop:null,pc:{x:17,y:13}}
};

/* ---- map data sanity: row lengths, warp/npc/trainer id references ---- */
(function(){
var errs = [];
Object.keys(G.Maps.LIST).forEach(function(id){
  var m = G.Maps.LIST[id];
  (m.tiles||[]).forEach(function(row, i){
    if(row.length !== m.w) errs.push(id+" row "+i+" len "+row.length+" != "+m.w);
    for(var c=0;c<row.length;c++){
      if("#.,~D=*soT ".indexOf(row[c]) < 0) errs.push(id+" row "+i+" bad tile '"+row[c]+"'");
    }
  });
  (m.warps||[]).forEach(function(w){ if(!G.Maps.LIST[w.to]) errs.push(id+" warp->"+w.to); });
  (m.trainers||[]).forEach(function(t){
    if(!G.Maps.TRAINERS[t.id]) errs.push(id+" trainer "+t.id);
    else (G.Maps.TRAINERS[t.id].party||[]).forEach(function(p){
      if(!G.Data.SPECIES[p.sp]) errs.push(id+" trainer "+t.id+" sp "+p.sp);
    });
  });
  function chkEnc(e){
    if(!e) return;
    (e.table||[]).forEach(function(x){ if(!G.Data.SPECIES[x.sp]) errs.push(id+" enc "+x.sp); });
    (e.water||[]).forEach(function(x){ if(!G.Data.SPECIES[x.sp]) errs.push(id+" water enc "+x.sp); });
  }
  chkEnc(m.encounters);
});
Object.keys(G.Maps.TRAINERS).forEach(function(id){
  var t = G.Maps.TRAINERS[id];
  (t.party||[]).forEach(function(p){ if(!G.Data.SPECIES[p.sp]) errs.push("trainer "+id+" sp "+p.sp); });
});
G.Maps._errors = errs;
})();
